### ISSUE TITLE
Scroll Position does not restore correctly 

### ISSUE THREAD

**Issue by atymic** [inertiajs/inertia#1012]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue3` version: 0.5.2

### Describe the problem:

When navigating via a `<Link>` with the `preserve-scroll` attribute, the scroll position is not restored. The scroll region is set up correctly, as using the back button/forward button sets the position correctly.

I jumped into the debugger, and it seems when setpage is called it's missing the scroll positions, but they are set correctly on the `window.history). They are set correctly before the visit is performed as well. See screenshots below.

![Screen Shot 2021-12-16 at 11 05 25@2x](https://user-images.githubusercontent.com/50683531/146284066-258317f6-b9df-480f-92f0-582abeaa9927.png)
<img width="1792" alt="Screen Shot 2021-12-16 at 11 08 07@2x" src="https://user-images.githubusercontent.com/50683531/146284259-067c4caa-9393-4998-9d0c-19942a8c535b.png">

<img width="1064" alt="Screen Shot 2021-12-16 at 11 06 35@2x" src="https://user-images.githubusercontent.com/50683531/146284127-f8abd06e-e770-4a3e-96a8-ab990c98365c.png">

### Steps to reproduce:

Will try to re-pro outside of app.

- Click <Link> element
- Note scroll position is not restored

**Comment by atymic** [comment]
Potentially worth noting I'm using vite. I built for prod and it also was failing there :(

**Comment by atymic** [comment]
Ok, I downloaded pingcrm to try to repro and noticed it had persistent layouts. I changed over and now the scroll preservation works as expect.

The docs don't mention you need to use persistent layouts anywhere. What i'm not sure is, is it a bug or intended behaviour that scroll preservation fails with non persistent layouts? 
https://inertiajs.com/scroll-management

**Comment by claudiodekker** [comment]
Hey @atymic,

This is just the nature of how components are mounted within their respective (adapter) libraries (vue, react ,svelte), and even within HTML. When the parent element (in this case, the layout) is 'replaced' or re-rendered, so do the children. 

Because of this re-rendering, the scroll preservation fails, as for a brief moment everything that's causing scrolling to exist in the first place is (to put it simple) 'removed' from your browser, and then re-inserted. The result is that your browser 'jumps' back to the top (no need to scroll when there's nothing to scroll, right?), and stays there when things are re-inserted.

With persistent layouts, we instruct these (adapter) libraries to render your page as a child of those layouts, and by doing that, the libraries won't re-render those when they don't need to, so this re-insertion doesn't happen.

Hope this explains.

**Comment by atymic** [comment]
Ahh right. Maybe it's worth adding to the docs that this is how the behaviour works, as it's not indicated :)
