### ISSUE TITLE
SSR window is undefined from router.ts

### ISSUE THREAD

**Issue by SuperDJ** [inertiajs/inertia#1047]
I'm trying to use SSR but running into some issues.

- vue: 2.16.14
- inertia: 0.11.0
- inertia-vue: 0.8.0

After compiling JS for SSR I get the following error from node:
>ReferenceError: window is not defined
    at e.n.isBackForwardVisit

Which seems to be related to the following:
https://github.com/inertiajs/inertia/blob/8597d5ee0243553a6373e9793acfe87739824750/packages/inertia/src/router.ts#L101

webpack.ssr.mix.js:
```js
mix.js( 'resources/js/ssr.js', 'public/js' )
    .vue({
        version: 2,
        options: { optimizeSSR: true },
        useVueStyleLoader: true, // Set to true or it will use style-loader which doesn't support SSR
    });

mix.disableNotifications();

mix.webpackConfig( {
        output: {
            chunkFilename: 'js/ssr_[name].js?id=[chunkhash]',
            globalObject: 'this'
        },

        target: 'node',
        externalsPresets: { node: true }, // Needed for Webpack 5 https://www.npmjs.com/package/webpack-node-externals
        externals: [webpackNodeExternals({
            modulesFromFile: {
                fileName: 'package.json',
                includeInBundle: 'dependencies',
                excludeFromBundle: 'devDependencies',
            }
        })],
```

dependencies from package.json:
```json
"dependencies": {
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue": "^0.8.0",
        "@inertiajs/server": "^0.1.0",
        "vue": "^2.6.12",
```

ssr.js:
```js
import Vue from 'vue';
import vuetify from './vuetify';
import { createRenderer } from 'vue-server-renderer';
import { createInertiaApp } from '@inertiajs/inertia-vue';
import { ZiggyVue } from 'ziggy';
import { Ziggy } from './ziggy';
import createServer from '@inertiajs/server';

 Vue.use(ZiggyVue);

createServer(page => createInertiaApp({
    page,
    render: createRenderer().renderToString,
    title: title => title ? `${title} | Company` : 'Laden... | Company',
    resolve: name => require(`@/pages/${name}`),
    setup({ App, props, plugin }) {
        Vue.use(plugin);

        return new Vue({
            vuetify,
            render: h => h(App, props),
        });
    },
}));
```

If I don't include the Inertia packages and Vue it will give an error like `vue not defined` or `@inertia/*` not defined. But using `@inertia/inertia` will return the mentioned error.

**Comment by SuperDJ** [comment]
@ajnsn & @claudiodekker,

Have created a minimal [repository](https://github.com/SuperDJ/inertia-ssr) to show the issue. After running `npm run watch` and `node public/js/ssr.js` you should see the error.

**Comment by claudiodekker** [comment]
Hey @SuperDJ,

So, it seems like this is coming from major changes to the way webpack compiles your app in SSR mode. Specifically, you're re-mapping the used externals here, which is what seems to be causing the problem:

```diff
- externals: [webpackNodeExternals()],
+ externals: [webpackNodeExternals({
+        modulesFromFile: {
+            fileName: 'package.json',
+            includeInBundle: 'dependencies',
+            excludeFromBundle: 'devDependencies',
+        }
+    })],
```

When reverting that single change and building, I get the following error:

```
/Users/claudiodekker/Code/inertia-ssr/node_modules/vuetify/lib/index.js:1
export * from './components';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.vuetify/lib (/Users/claudiodekker/Code/inertia-ssr/public/js/ssr.js:1745:18)
    at __webpack_require__ (/Users/claudiodekker/Code/inertia-ssr/public/js/ssr.js:1769:42)
    at Module../resources/js/vuetify.js (/Users/claudiodekker/Code/inertia-ssr/public/js/ssr.js:17:69)
```


This error then signals to me that Vuetify isn't compatible with _the currently configured Node environment_, but since I'm not trying to fix Vuetify right now and am instead trying to figure out what part of the app is causing Inertia's SSR to break, I removed the Vuetify references / import, at which point compilation succeeded **and** Inertia's SSR works as intended.

In turn, this then tells me that the error can be coming from two places:
1. The webpack configuration being invalid
2. Vuetify not being compatible with Node-environments/SSR.

Because the webpack adjustment was likely done to prevent Vuetify from 'crashing' with the error above, this tells me that it's also likely that if I reset the webpack change only (keeping Vuetify out for now), I will see the 'window is undefined' error again, which I did, **proving that the issue is not with Inertia but rather with your webpack (re)configuration**.

I do realize that this "fix" was likely done to get Vuetify to work, but just because something doesn't scream at you during compilation does not mean that it works. Unfortunately, I also do not have a fix for Vuetify, you'd have to open an issue there if you want to use it in SSR mode (assuming that you need it in SSR at all?)

**Comment by SuperDJ** [comment]
@claudiodekker I added lines
```js
+ externals: [webpackNodeExternals({
+        modulesFromFile: {
+            fileName: 'package.json',
+            includeInBundle: 'dependencies',
+            excludeFromBundle: 'devDependencies',
+        }
+    })],
```
to prevent the error below from `ssr.js`:
>Error: Cannot find module 'vue'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

That error points towards these lines:
```js
/***/ "vue":
/*!**********************!*\
  !*** external "vue" ***!
  \**********************/
/***/ ((module) => {

"use strict";
module.exports = require("vue");
```

```js
/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			id: moduleId,
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId].call(module.exports, module, module.exports, __webpack_require__); // This specific line
```

```js
"use strict";
/*!*****************************!*\
  !*** ./resources/js/ssr.js ***!
  \*****************************/
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var vue__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! vue */ "vue"); // This line
```

```js
if (false) {} else {
  vue__WEBPACK_IMPORTED_MODULE_0___default().use(ziggy__WEBPACK_IMPORTED_MODULE_3__.ZiggyVue);
}

_inertiajs_server__WEBPACK_IMPORTED_MODULE_5___default()(function (page) {
  return (0,_inertiajs_inertia_vue__WEBPACK_IMPORTED_MODULE_2__.createInertiaApp)({
    page: page,
    render: (0,vue_server_renderer__WEBPACK_IMPORTED_MODULE_1__.createRenderer)().renderToString,
    title: function title(_title) {
      return _title ? "".concat(_title, " | CadixCas") : 'Laden... | CadixCas';
    },
    resolve: function resolve(name) {
      return __webpack_require__("./resources/js/pages sync recursive ^\\.\\/.*$")("./".concat(name));
    },
    setup: function setup(_ref) {
      var App = _ref.App,
          props = _ref.props,
          plugin = _ref.plugin;
      vue__WEBPACK_IMPORTED_MODULE_0___default().use(plugin);
      return new (vue__WEBPACK_IMPORTED_MODULE_0___default())({
        render: function render(h) {
          return h(App, props);
        }
      });
    }
  });
});
})(); // This line
```

**Comment by claudiodekker** [comment]
That most likely means you haven't installed Vue then. 

When running a simple npm/yarn install from your reproducable repository, I was able to reproduce the bug you mentioned in the issue description, but never ran into this problem.

**Comment by Froxz** [comment]
@SuperDJ did you find a solution for this? have the same issue.

**Comment by Froxz** [comment]
@claudiodekker @SuperDJ if still interested to make SSR with vuetify + inertia:

For some reason when importing:

```js
import Vuetify from 'vuetify'
```

`this.$isServer` - becomes false ( I couldn't find the exact reason why this happens)

But if importing from source
```js
import Vuetify from 'vuetify/lib'
```
throws an error because `node` can't use imports if not in `module` .

The solution is to use `import Vuetify from 'vuetify/lib'` and `VuetifyLoaderPlugin`

Laravel-mix config
```js
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

mix.webpackConfig({
      target: 'node',
      externals: [nodeExternals({
          allowlist: [/^vuetify/] //Transpile vutify and include in build
      })],
      plugins: [
          new VuetifyLoaderPlugin()
      ]
});
```
