### ISSUE TITLE
Is there a way to customize the colour of the progress indicator on different pages/Vue-component?

### ISSUE THREAD

**Issue by jameswong3388** [inertiajs/inertia#1138]
### Versions:

- `@inertiajs/inertia` version: ^0.11.0
- `@inertiajs/inertia-vue3` version: ^0.6.0

### Describe the problem:
Is there a way to customize the colour of the progress indicator on different pages/Vue-component?

For example, on the home page I have a black indicator, then a dashboard using a white indicator.

Any answer would be appreciated!

**Comment by jonagoldman** [comment]
Option 1: Disable the default styles  `InertiaProgress.init({ includeCSS: false })` and use your own styles and classes in each component.

Option 2: Use NProgress directly instead of the Inertia wrapper and provide your custom css file.

This is explained in [Progress indicators](https://inertiajs.com/progress-indicators)

The progress indicator is just a wrapper around NProgress.

**Comment by james-wong123** [comment]
@jonagoldman, how exactly apply your own styles and classes in each component?
