### ISSUE TITLE
How to prevent from from submission

### ISSUE THREAD

**Issue by nezaboravi** [inertiajs/inertia#1232]
### Discussed in https://github.com/inertiajs/inertia/discussions/1226

<div type='discussions-op-text'>

<sup>Originally posted by **nezaboravi** July 15, 2022</sup>
Hello
My business logic requires to have a Submit button disabled unless all the form data (or at least required ones) are filled up.
Form is pretty long and growing.
Current state is here:
```
const form = useForm({
    user: {
        email: ref(null),
        name: ref(null),
    },
    company: {
        bankDetails: ref(null),
        address: ref(null),
        additionalInfo: ref(null)
    },
    billing: {
        name: ref(null),
        address: ref(null),
        email: ref(null)
    },
    invoice: {
        prefix: ref(null),
        number: ref(null),
        invoiceDate: ref(moment()),
        invoiceDueDate: ref(moment())
    }
})
```

in the template part, i will have a button Submit, which shall be disabled by default.

IN the background i have working Laravel app to validate form.
I could make something to check for each field is empty and once if its not empty, i enable button, but does not seems to me like great idea.
How do i keep Submit button disabled until all the fields are properly filled up?
</div>

**Comment by Tofandel** [comment]
You shouldn't open issues of things that have nothing to do with inertia, should have kept it in Discussion which was the right place for that

This basically depends on your frontend framework, if you're using a full framework like quasar you would use `QForm` and `rules` on your inputs

Otherwise you'd need to use something like [vee-validate](https://vee-validate.logaretm.com/v4/)

**Comment by nezaboravi** [comment]
> 
Thank you for the reply. No one replied on discussions, so i tried to level up a issue i am having problem with. 
This is not exactly an issue, but would not be a great idea to have something like focusOnFirstError() ?
or useForm.preventSubmit?
If i know how, i would happily make a PR. :)

Inertia has useForm() as it is in my code example, so, really i might be on wrong place and this is not related to inertia js by J.Reinik, in fact, inertia-vue3 ? 

If so, i deeply apologize. If this is inertia js  github, and there is no specific part of inertiajs where i can suggest, ask, or look for help, then my question has everything with inertia. 

My question is **how to keep Inertia.js useForm() disabled until all the required fields are filled**?

useForm() is part of Inertia, is it not? If it is, then it does have everything with inertia. If is it not, again, i appologize, and i will remove my question.

I dislike your answer, as you started with 'you should not open..', yet you never tried to help on discussion on this matter in 5 days. I know, this is not something you must answer. It is just a matter of your good will. Or anyone else.
And not much value in your answer, after all as you suggesting to bring up a third party lib for that matter, and ignore useForm() as i suppose those two will not dance.

**Comment by Tofandel** [comment]
Well first of all, inertia is a monolithic server side router for modern applications and js frameworks, nowhere does it says it's a form validation plugin 

useForm is just a convenience that was added to simplify form submission

You wouldn't ask vue-router for form validation would you? 

Adding validation rules is in the scope of other plugins to do which then you can use to disable the submit button or display error messages, there is already so many out there that are very good, complete and plug and play that it makes 0 sense to add it to inertia, and no you don't need to drop useForm, they're complementary, because useForm is renderless and basically just a ref wrapper with some logic baked into, and validation plugins are meant to be added to rendered elements directly (inputs, etc) 

You're right, as a developer it's your job to research your problem and find a solution (which you could have done very easily with a bit of googling) and not the job of unpaid volunteers to do that for you

Issues are only for reproducible bugs or feature requests with a minimum of effort put into it, same for every repo and there and nobody will ever tell you differently 

What it's not for is to reply to very broad and undetailed questions of a developer who didn't do his homework 😉

Am I (me a simple contributor having little to do with inertia) supposed to monitor discussions h24 and answer them straight away? Obviously not. You'll only get answers from people who stumble onto your thread because they were around and think they can help. 5 days is nothing for open source

If you didn't get an answer in the first place I'd just suggest putting more effort into presenting your problem better, trying things and proofreading. Because as I said, if you didn't do your due diligence, we won't do it for you and won't waste time on poor quality discussions

**Comment by nezaboravi** [comment]
You are very rude in polite way. 
You should do kindness of reading someones question first. 
I have never asked how to validate form and never said I expected useForm() will do a validation.
I exactly know what useForm is, and how it works. 
As I am merely a developer learning inertia, I tried to ask people on GitHub to address the specific question that you did not read, twice, and **is not how to validate form**. 
Just how to focus on first error, as focusOnFirstError() as I can't find anything similar to it in api and if its possible to disable submit button. 
Maybe Mr Reinink had that somewhere in api, that is not in documentation. 
And then you are lecturing me and explaining me that this is not form validator. Hilarious.



Your comments are very rude and offending, such "You're right, as a developer it's your job to research your problem and find a solution (which you could have done very easily with a bit of googling) and not the job of unpaid volunteers to do that for you" - please will you do it for me? I would love to see what you gonna google. That is just dumb thing to say.
If there was easy solution on google, would I land here and bother others? 
How rude is that?

You said "I am a developer who did not do his homework", and yet AGAIN, you did not read carefully my question. What homework dude? Have you tried to google how to land on first filed in form on error with inertia js?

You are really just a simple contributor, and I have never said or expect that you are or anyone else are supposed to monitor and answer. I greatly appreciate everyone who contribute and trying to help people. 

What I said is that your answer is offending and useless as you did not bother to try to understand and read it thorough.
Would it not be better to say something, like, hey sir, could you elaborate more? We don't understand the problem?
I still failing to se what is there not to understand? 

Instead you pointing me to vue-validate? Who was asking validation?

And in your next answer offending me saying I am lazy and expecting others to solve my problem. 
You say: "and no you don't need to drop useForm" - do you think I have not read docs? Actually it is recommended there to use it, however, yes I know I don't need to use it.
Here is for you, from docs "While it's possible to make classic form submissions with Inertia, it's not recommended, as they cause full page reloads. Instead, it's better to intercept form submissions and then make the request using Inertia."

Could you not simply say- we do not have a way to disable submit button? Or, I don't know how you can do that? Or, nothing? 

You are so stubborn in your answers and you are answering a question I have never asked. In that fire you are asking me to compare due router and validation - again- who asked how to validate?

**You are talking about validation, which I said, clearly I hope, I did on backend in Laravel, and I merely asked is there a way to focus on first error and disable button until is done.** 

Presenting issue - maybe you just don't understand, so I am wondering why you commented at all if you did not understand it?

You are the one who is not reading issue. 
I have never asked how to validate. I said I am validating it in backend. No one ever asked that and both your answers are based on it. 

You said: " inertia is a monolithic server side router for modern applications and js frameworks, nowhere does it says it's a form validation plugin" - did I implied anywhere I was expecting it to be a form validation plugin?

I have closed this as issue earlier today before you made another useless and careless, offensive answer.
I have tried to polite and I chose my words, yet you offend me calling me lazy person who did not do his homework. 
And you don't even know what homework was. 
Again, shame on you.

Read kid, and read carefully, think twice before you say something. Do not offend people with your answers. Ask politely when you are not sure you understand. Ask for more information. If something is not explained well, ask for more, do not attack. What is well explained for one, maybe is not for another. We are all different. Some smart, some smarter. Some rude, some polite. Again, read. Be nice. Respect others.

Respect

**Comment by Tofandel** [comment]
Look I'm not even gonna read that, I did understand your issue and explained where you can find your ressources, now please look at them before saying it's not what you're looking for. I won't reply anymore.
