### ISSUE TITLE
Make the progress bar optional

### ISSUE THREAD

**Issue by francoisauclair911** [inertiajs/inertia#124]
Hi,
I know you guys are planing on adding more customization for the progress bar and I was wondering if it would be a good idea to make the progress bar optional on some requests

**Proposition**
Adding a `showProgress` props to the request and also `inertia-link` component
This props would be evaluated in the inertia.js and disable the progress bar if props is true

```
this.$inertia.post(url, data, {
  replace: false,
  preserveState: true,
  preserveScroll: false,
  only: [],
  showProgress: false,
})
```
`<inertia-link href="/posts" showProgress="false" method="post">Save</inertia-link>
`

**Comment by francoisauclair911** [comment]
see PR https://github.com/inertiajs/inertia/pull/125

**Comment by reinink** [comment]
I'm curious, why would you want to disable the progress bar for specific requests? This seem unnecessary...but maybe I'm missing something?

**Comment by reinink** [comment]
Closing this for now, because there hasn't been any other demand for this, and I don't really see the use-case myself.

@francoisauclair911 Feel free to provide your reasons, and we can always revisit.

**Comment by anubra266** [comment]
I actually think this is useful.
Use Case: I want to mark a notification as read, The user should not see a progress bar every time he clicks a notification, should he?
I found this thread while searching for a solution to this. Please implement it.

**Comment by reinink** [comment]
> The user should not see a progress bar every time he clicks a notification, should he?

I kind of think the user *should* see a progress bar any time a request is occurring, and taking longer than the 250ms threshold, since with Inertia a synchronous page load is happening, and not just some "background" asynchronous xhr/fetch request that's clearing the notification. If you want the later behaviour, then I'm inclined to suggest just using xhr/fetch directly to do this, and not make an Inertia request.

**Comment by claudiodekker** [comment]
Hi @anubra266,

As of last month, the progress bar is an entirely separate package (https://github.com/inertiajs/progress) with a default (yet configurable) delay of 250ms. Since _most_ simple requests finish between 60-120ms or so, we don't believe this should be a real issue for virtually anyone, unless they are on a _very slow_ or unstable connection, in which case they might actually want to see a progress bar to indicate that something is happening.

That said, we're more than open to being proven wrong, so if you think we're mistaken or are missing something, please let us know by commenting on this issue, and we'd be more than happy to consider the situation and re-open this issue!

**Comment by anubra266** [comment]
> If you want the later behaviour, then I'm inclined to suggest just using xhr/fetch directly to do this, and not make an Inertia request.

Regarding this, I just feel it'll be great to have Inertia cover most cases, as some of us - including me have decided that Inertia is my Primary Stack for all projects. Having to use Inertia, and still fallback to the old way in all my projects seems unneccessary.

**Comment by anubra266** [comment]
Thanks for your reply @claudiodekker 

You should know you now have fans all over the world.
Take me for example, I stay in Nigeria, West Africa.
Fast Internet Connections is not a Luxury to me as a Developer. Definitely not to my users. I'm currently working on an Elearning site, the 2.0 version. I'm rebuilding the site in Inertia, to give my users a smoother and realtime experience, my users are basically, students from public schools. A public school here could not get a paid Elearning site in 100 years to come.

Sorry for the long story, but my point is we can't assume a fast Internet connection for everyone.

Thanks again.

**Comment by reinink** [comment]
> Having to use Inertia, and still fallback to the old way in all my projects seems unneccessary.

We get this more often, and I totally don't think this is the right way of looking at it. Rather, these are simply two different tools at your disposal. Use Inertia when making page visits, and use xhr/fetch when doing other asynchronous tasks.

It doesn't have to be one or the other. Both tools have their place...and I use both in my Inertia apps!

**Comment by reinink** [comment]
> Fast Internet Connections is not a Luxury to me as a Developer.

And to be clear, I understand the not everyone has fast internet connections...which is arguably my point. Users should be aware that a slow request is still being sent...otherwise they could click on a different link and actually cause the "clear notification" request to get cancelled.

**Comment by anubra266** [comment]
Thanks @reinink 
I'll take the manual xhr approach.

**Comment by reinink** [comment]
Reopening this issue, because there is other demand for it (#310, #311), plus, I'm starting to see a use-case for this for lazily evaluated props, that are loaded "in the background".

```js
Inertia.reload({ only: ['something'], hideProgress: true })
```

**Comment by anubra266** [comment]
Oh thank you @reinink

**Comment by reinink** [comment]
To be clear though, all Inertia visits are still synchronous, so still can't use them for polling. See my comment [here](https://github.com/inertiajs/inertia/issues/310#issuecomment-720499160).

If you want async behaviour, then you need to use xhr/fetch.

**Comment by anubra266** [comment]
Ok... Understood
