### ISSUE TITLE
InertiaJS does not have enough maintainers to handle the number of open issues and pull requests

### ISSUE THREAD

**Issue by nyatalieee** [inertiajs/inertia#1240]
### Describe the problem:

Let me preface this with: I adore Inertia, both the backend and frontend. I think it's fantastic and @reinink has done a wonderful job creating it.

Now, I appreciate this repository is open source under the MIT license and relies on sponsorship to fund, however **this repository simply does not have enough maintainers to handle the number of open issues and pull requests**.

**Examples of problems this has caused:**
- This repository has open pull requests from 2020. If the code or changes are not desired, close them!
- Pull requests take months to be responded to or merged. At the time of writing, the last merged pull request was 2 months ago.
- There are 101 open issues, the majority of which have no response from a maintainer, just other users reporting the same issue.

### Suggestion:

Consider adding more repository maintainers that are willing to help. Some maintainers responsible for react, svelte, vue, etc.

**Please do _something_ to address the extremely slow response to issues and pull requests.**

Thank you for your time.

**Comment by reinink** [comment]
Hey,

I appreciate that it's frustrating that issues don't get fix or PRs don't get merged in, but I don't think your expectations on open-source are reasonable. Inertia.js is not a service/business that I run. It's a library that I created to serve my own needs on my own projects. I decided to make it available freely to others to use, but that doesn't come with any guarantees — if it works for you, amazing, but if it it doesn't, then you're of course welcome to fork it, or just not use it at all.

Finding additional maintainers also isn't as simple as it sounds. It's actually extremely hard. It's like finding a business partner who shares the same skillet and values as you. Simply adding maintainers to the project at this point would actually just create more work for me, as it would require lots of conversations and training.

Don't get me wrong, I love Inertia, and I hope to see the project continue to grow and improve. In the background work is being done — one thing I've been doing recently is finding ways to make the project easier to maintain moving forward, since it's quite complicated right now, which slows down the development process.

But ultimately, at the end of the day, I work on this project as I have time, and as it's enjoyable and fulfilling for me to do. If that means that Inertia isn't the "next big thing", I am totally okay with that. It's more important for me that I maintain a healthy work/life balance.

I hope that makes sense.
