### ISSUE TITLE
Understanding Inertia Version

### ISSUE THREAD

**Issue by roarkmccolgan** [inertiajs/inertia#133]
Hi Guys,

Not an issue but rather clarification please.

Looking at the PingCrm app you use mix versioning in AppServiceProvider
```php
Inertia::version(function () {
    return md5_file(public_path('mix-manifest.json'));
});
```
As the gitignore file includes:
```
/public/mix-manifest.json
```
The file is not found when I deploy so I get an error.
Are you building for production on the server? or should I just remove the line form gitignore?

Thanks so much

**Comment by Juhlinus** [comment]
Hello @roarkmccolgan !

You should build on the server.

**Comment by roarkmccolgan** [comment]
Thanks for the quick response @Juhlinus 
I have done so and it works as expected.

I actually never build on the server, is this common practice for all app types, not just inertiajs?
_asking for a friend_ 🤣

**Comment by Juhlinus** [comment]
@roarkmccolgan 

It's common to build and test on the server itself so that you can be sure that everything works as they should on your production environment. 🙂 This is usually done in the staging environment. Which can be on the production server, but not actually accessible from anywhere. When all tests are done and everything is compiled you point the production code towards the newly deployed code.

https://www.digitalocean.com/community/tutorials/an-introduction-to-continuous-integration-delivery-and-deployment

**Comment by roarkmccolgan** [comment]
Nice!

Thanks for the description and reference, I will have a run through it!
