### ISSUE TITLE
Browser back button not preserving scroll position when using Firefox

### ISSUE THREAD

**Issue by ivanmagdic** [inertiajs/inertia#138]
I was testing Inertia.js and Vue.js and come upon a strange behavior when using Firefox. Firefox does not preserve the scroll position when going back (pressing the browser back button), but Google Chrome does.

I am testing on my demo app that you can view here: http://gamebrowser.imagdic.me/ with following code: https://github.com/ivanmagdic/laravel-gamebrowser

Reproduce: Just scroll down a little bit on the game list, press on any game, and then press back button in the browser.

Is this a Vue or maybe an Inertia problem? Any explanation is welcome.

Firefox is: 76.0.1 (64-bit) Tried also with Brave & Google Chrome and those preserve scroll when going page back. (Chromium-based)

**Comment by ivanmagdic** [comment]
Found temporarily fix for this issue:
https://github.com/janpaul123/delayed-scroll-restoration-polyfill

**Comment by Juhlinus** [comment]
@sebastiandedeyne the mentioned polyfill isn't really that big, but it might be beneficial to extract the functionality and add it to inertia. Thoughts?

**Comment by sebastiandedeyne** [comment]
I'm not really familiar with the scroll restoration behaviour myself, gonna need to dig into this with @reinink later on.

**Comment by reinink** [comment]
@ivanmagdic I'm actually really surprised you're having this issue in Firefox. Inertia really just relies on the default browser behaviour for this when you're not using scroll regions (meaning the whole document is scrollable).

One work around here is to use a scroll region instead of of having the whole document scrollable. That way Inertia will keep track of the scroll regions and automatically the scroll positions for you.

That said, I would want scroll restoration to work in Firefox regardless of that. I'll have to do some more testing to see if I can reproduce this.

**Comment by claudiodekker** [comment]
@reinink Apparently Firefox triggers `scroll` before `popState`: 
- https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration
- https://bugzilla.mozilla.org/show_bug.cgi?id=679458

**Comment by reinink** [comment]
@claudiodekker I don't think so.

I just tried PingCRM with the latest version of Inertia on the latest version of Firefox, and it works as expected. However, it doesn't work on http://gamebrowser.imagdic.me/.

I think there was a bug with this early on that got fixed, meaning this is no longer an issue.

@ivanmagdic If you wanted to update this app to the latest version of Inertia.js and verify, that would be appreciated. For now I'm going to assume it's fixed and close this issue. If anyone can reproduce this problem on the latest version of Inertia.js, I'll gladly reopen. 👍
