### ISSUE TITLE
Cached response return non-inertia response

### ISSUE THREAD

**Issue by itsfaqih** [inertiajs/inertia#154]
My Inertia app sometimes showing a modal with an iframe instead of changing the page when I click a link.

![image](https://user-images.githubusercontent.com/48067039/88121195-3381fa80-cbef-11ea-8221-bf0115ca3444.png)

I heard that this happens when the response is not an inertia response, but as you can see in my every controller, it always return an inertia render function:
https://github.com/itsfaqih/laravel-react-inertiajs-tailwind/tree/master/app/Http/Controllers
It also happened to the demo app (pingcrm) if I hosted it online, but it works well in localhost.

Later, I found out that there's a difference in response header whenever this problem occured. The modal will show if the cache-control value is public and max-age=n

![image](https://user-images.githubusercontent.com/48067039/88121595-70022600-cbf0-11ea-9e46-dcf058b5b2ec.png)

While in localhost, it never happened because the cache-control value is always no-cache, private
![image](https://user-images.githubusercontent.com/48067039/88121654-a049c480-cbf0-11ea-9f9f-7f4ddb299377.png)

I'm actually not really sure if the cache-control caused it because I can't test (set the cache-control value) it in my online hosting due to its limitation. But if it is, is there anyway how to fix this?

You can also try the website here: https://jurnalfilm.com
username: johndoe@example.com, pass: secret
Try to login then clicking the logo and home menu repeatedly

**Comment by claudiodekker** [comment]
Hi,

Even though this issue is more suited over at https://github.com/inertiajs/inertia-laravel, I'll do my best to answer it here.

---

When you call a page using either the [`<inertia-link>` component](https://inertiajs.com/links) or an [Inertia XHR request](https://inertiajs.com/forms#classic-xhr-submits), Inertia sets the `X-Inertia` header on the request:
![Screenshot 2020-07-28 at 21 36 06](https://user-images.githubusercontent.com/1752195/88712661-5a25c100-d11a-11ea-84d3-7924e6a66e4c.png)

What happens on the back-end, is that as your request travels through your Laravel app, it will eventually hit the `Inertia::render(..)` call once again. Inside this call, the back-end part of Inertia will check whether the request was made by Inertia's client-side (by checking for this `X-Inertia header`), or whether it was a normal browser's request to load a page. Here's a link to where that exact piece of logic happens on the back-end: https://github.com/inertiajs/inertia-laravel/blob/e7b95274dc0f6d4148380e2c45ba1c94f77c1c9c/src/Response.php#L83

If it determines that the request came from Inertia's client-side, it creates a custom JSON response, and once again sets the `X-Inertia` header, to make sure that the front-end is aware that what it is receiving is not a 'regular' HTML/JSON API response, but an Inertia response that tells Inertia what to do.

So, to summarize, here's a step-by-step process of how the flow works:
1. Visitor browses to example.com
2. Inertia's back-end doesn't detect the `X-Inertia` header, so renders a full HTML page response.
3. Visitor's browser receives full HTML, renders the CSS, Javascript (which includes Inertia's client side), and is done.

4. Visitor clicks on an `<inertia-link>`-component link.
5. Inertia interrupts the actual browser navigation, creates a custom request, adds the `X-Inertia` header on it, and sends it to the back-end.
6. Inertia's back-end detects the `X-Inertia` header, so renders a Inertia-specific JSON request
7. Inertia's front end receives the response, sees the `X-Inertia` header, and uses it to 'change' the page.

So, long story short, it's most likely not the Cache header that's causing you problems.
I tried replicating it on your website, but everything seems to work fine. Could it be that you already solved it?

**Comment by itsfaqih** [comment]
Hi, thanks for responding!

> Even though this issue is more suited over at https://github.com/inertiajs/inertia-laravel, I'll do my best to answer it here.

Sorry I was kind of confused about where should I create the issue back then. I guess because if it's using laravel then I should've post it there.

> So, long story short, it's most likely not the Cache header that's causing you problems, but rather that the X-Inertia header is missing.

I agree. After trying to reproduce it in local (changing the cache header), apparently it doesn't cause the bug.

> I tried replicating it on your website, but everything seems to work fine. Could it be that you already solved it?

Nope I haven't, and it still happening to me

![image](https://user-images.githubusercontent.com/48067039/88720147-97a44180-d14e-11ea-939a-6337d5c961eb.png)

I don't know why, but sometimes it can works fine, sometimes it bugged like in the screenshot.
I think the one who caused the problem is the hosting provider that somehow removed the X-Inertia header. I have moved my website to another hosting and this problem doesn't happen anymore.

Since it's not a problem from the inertia, I'm closing this issue.
Once again, thank you!
