### ISSUE TITLE
Reuse resolveComponent callback for dynamic component resolution

### ISSUE THREAD

**Issue by daniser** [inertiajs/inertia#1548]
### Versions:

- `@inertiajs/core` version: 1.0.6

### Describe the problem:

It'd be cool to reuse page resolution logic to resolve [dynamic components](https://vuejs.org/guide/essentials/component-basics.html#dynamic-components), for example, page partials.

As of now, `router.resolveComponent` method is protected.
There may be some way to access `resolveComponent` callback from somewhere outside of router, but I can't find a way to do it gracefully.

### Steps to reproduce:

```php
<?php

use Illuminate\Routing\Controller;
use Inertia\Inertia;
use Inertia\Response as InertiaResponse;

class SomeController extends Controller
{
    public function index(): InertiaResponse
    {
        // here needs to be some logic to resolve page partial on the backend
        $component = 'SomePagePartial';

        return Inertia::render('SomePage', compact('component'));
    }
}
```

```vue
<template>
    <component :is="dynamicPartial" />
</template>

<script setup>
import { ref, onBeforeMount } from 'vue'
import { router } from '@inertiajs/core'

const props = defineProps({
    component: String
})

const dynamicPartial = ref()
onBeforeMount(async () => {
    dynamicPartial.value = await router.resolveComponent(props.component)
})
</script>
```

**Comment by reinink** [comment]
Hey! So interesting idea, but I've never built anything like this with Inertia, and to be honest it kind of feels strange to load one Inertia page inside another Inertia page — especially since these partials wouldn't be provided the page props like a normal page.

I'm going to close this one for now, but if we get more interest for this from others we can always revisit it in the future.

Thanks for sharing the idea either way!
