### ISSUE TITLE
Add a .NET Core Server Side Adapter

### ISSUE THREAD

**Issue by pdevito3** [inertiajs/inertia#156]
Not sure on feasibility here, but might be cool to have a .NET Core adapter as well. Adding this in to hopefully look at it in the next couple of weeks, but if someone beats me to it go for it!

**Comment by ycs77** [comment]
https://github.com/Nothing-Works/inertia-aspnetcore

**Comment by pdevito3** [comment]
Sweet. @reinink any reason this isn't in the officially supported library?

**Comment by reinink** [comment]
Mostly because it's really hard for us to maintain all the possible adapters, since it requires deep knowledge of those languages and frameworks.

If there are really high-quality adapters that implement all the features of Inertia.js, with a solid test suite, we will consider taking them on as official adapters, but even then we'll still need outside help to maintain them.

I'd love to see adapters start as 3rd party adapters, and if they grow in popularity, and are somewhat battle tested, then we move them over to official adapters.

I hope that makes sense! 👍

**Comment by pdevito3** [comment]
Absolutely. Figured as much, but just making sure. Will try and block out some time to help beef it up to first party quality for ya.

**Comment by reinink** [comment]
@pdevito3 Awesome Paul, thanks! 🙌

**Comment by nathandaly** [comment]
Shame .NET is a big one :)
