### ISSUE TITLE
CSRF 419 error - token is no longer refreshed 

### ISSUE THREAD

**Issue by xhava** [inertiajs/inertia#1576]
### Version:

"inertiajs/inertia-laravel": "^0.6.8"

### Describe the problem:

The problem is that after the lifetime expiration session value = 120 minutes the csfr token is  no longer refreshed, no matter if I refresh the browser.

The only way to generate a new token is to delete all session data and cookies from the browser.

i don´t have a meta tag for the csrf, i have read that this can cause some ploblems but i am not using it. 

### Steps to reproduce:

1.- open the site in the browser, 
2.- leave the site unused for the time defined in the session lifetime variable in the .env file, I have 120
3.- enter the application again and it shows error 419 when making a request post, no matter if I refresh the browser, it does not generate a new value for the token. the only way to generate the token again is to clear the site's session data and cookies. 

i am using SSR, i have client side hydratation enabled, and i have run the inertia command to run the server php artisan inertia:start-ssr

<img width="1505" alt="Captura de pantalla 2023-05-30 a la(s) 23 27 45" src="https://github.com/inertiajs/inertia/assets/4241380/d894d9f5-e00b-4e41-88c3-4676b4d788c2">

**Comment by reinink** [comment]
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Comment by lubuger** [comment]
no it's not resolved, got this error today

**Comment by lubuger** [comment]
what could be a solution is:

in bootstrap/app.php file add this one (which is related to https://inertiajs.com/csrf-protection)

`
->withExceptions(function (Exceptions $exceptions) {
        $exceptions->respond(function ($response) {
            if ($response->getStatusCode() === 419) {

                return back()->with([
                    'message' => 'The page expired, please try again.',
                ])->header('Clear-Site-Data', '"*"');
            }

            return $response;
        });
    })
`
