### ISSUE TITLE
Inertia useRemember load states only once

### ISSUE THREAD

**Issue by RezaMnk** [inertiajs/inertia#1588]
### Version:

- `@inertiajs/react` version: 1.0.0

### Describe the problem:

Inertiajs useRemember hook, loads states only once when the page refresh and after changing route, the state will lose totally.

### How i use the hook:

```
import {useRemember} from "@inertiajs/react";
const [dark, setDark] = useRemember(false);
```

### How i change the state:

`<button onClick={() => setDark(! dark)}>`

**Comment by RezaMnk** [comment]
well I used another method to do the trick:

`    const [dark, setDark] = useState(
        localStorage.getItem('dark') === 'true'
    );

    useEffect(() => {
        localStorage.setItem('dark', dark);
    }, [dark]);`

But the bug for setRemember still exists and it's not working anyway

**Comment by reinink** [comment]
Hey! Just a heads up here that `useRemember` is intended for remembering data in the history state — when going forward and back in your browser history. This isn't an alternative to using local storage.

I just tested this feature out using our React playground and everything seems to be working, so I suspect this is just a misunderstanding about how this feature is intended to be used.

Glad you found a solution 👍

**Comment by sakihl** [comment]
> Hey! Just a heads up here that `useRemember` is intended for remembering data in the history state — when going forward and back in your browser history. This isn't an alternative to using local storage.
> 
> I just tested this feature out using our React playground and everything seems to be working, so I suspect this is just a misunderstanding about how this feature is intended to be used.
> 
> Glad you found a solution 👍

Hi @reinink 
I have just found this comment which has saved me from spending a lot more time because I was caught out by the same misunderstanding. I had not registered that it was only for going forward and back in the browser history. Looking at the documentation on [Remembering state](https://inertiajs.com/remembering-state) with fresh eyes I now see that it clearly starts with the words "When navigating browser history" but I nonetheless managed to think it would work when navigating to the page again from elsewhere in the application.

Might you consider putting a note in the documentation just to point this out explicitly to others who might make the same mistake, just as you have done above?

> Note:  `useRemember` is intended for remembering data in the history state — when going forward and back in your browser history. This isn't an alternative to using local storage to preserve state between pages.

**Comment by rudolfbruder** [comment]
I still dont get it. I have a simple two pages. On one I have a form with title, on second page there is nothing just some parapgrah and button which is a Link component and links to /step-one

Once i fill in step one page hit redirect to page two, then click the browser back button the value of title is not restored. Its also not restored if I navigate back via router.visit('/step-one') which I get because its only supposed to work when using forward and back buttons in browser right?

When I open page one, fill in title, redirect to some non inertia page then hit back in the browser it works and the title field is prepopulated once. If i refresh the page its gone which is okay.

But for me it does not work when I redirect back using browser button between two inertia pages.

@reinink @sakihl it should work right? Am I missing something please?

**Comment by sakihl** [comment]
Hi @rudolfbruder I'm sorry I cannot help you. I am just a user of Inertia, not an expert. After I made my comment on this thread I stopped trying to use useRemember as it was inappropriate for the particular behaviour I needed in my application, and switched to using a Pinia store to preserve state between pages more generally.

**Comment by neilcode** [comment]
> I still dont get it. I have a simple two pages. On one I have a form with title, on second page there is nothing just some parapgrah and button which is a Link component and links to /step-one
> 
> Once i fill in step one page hit redirect to page two, then click the browser back button the value of title is not restored. Its also not restored if I navigate back via router.visit('/step-one') which I get because its only supposed to work when using forward and back buttons in browser right?
> 
> When I open page one, fill in title, redirect to some non inertia page then hit back in the browser it works and the title field is prepopulated once. If i refresh the page its gone which is okay.
> 
> But for me it does not work when I redirect back using browser button between two inertia pages.
> 
> [@reinink](https://github.com/reinink) [@sakihl](https://github.com/sakihl) it should work right? Am I missing something please?

Also not an expert, but here's my take: I think this is the intended behavior. A redirect back to a page you've visited previously is not going to make use of browser history at all. `useRemember` it strictly for remembering state when using the back and forward buttons in your browser. 

If you want to remember state between pages as you're describing, you'll want to use `preserveState` in your inertia link or `router.visit` calls.
