### ISSUE TITLE
Reloading adds to the history

### ISSUE THREAD

**Issue by scottzirkel** [inertiajs/inertia#16]
Not sure if it's related to #6 or not, but when you reload the page, it adds the current page to the browser history.

**Comment by reinink** [comment]
Hi @scottzirkel, you're using the inertia-laravel adapter correct? Can you try updating it? I think that's the issue here.

Reason why: Inertia now expects the `url` to always be present, even on the initial page load. The Laravel adapter handles this for you as of [this commit](https://github.com/inertiajs/inertia-laravel/commit/d22b42840936f377ba77cef563332f7e544b91ef).

**Comment by scottzirkel** [comment]
Yes, sorry. I wiped the vendor folder and reinstalled before starting, but forgot about composer lock. My bad. Carry on.

**Comment by reinink** [comment]
👍
