### ISSUE TITLE
Error on site. 404 link. Need documentation issues.

### ISSUE THREAD

**Issue by vobar** [inertiajs/inertia#1653]
### Versions:

- `@inertiajs/core` version: #.#.#
- `@inertiajs/vue2` version: #.#.#
- `@inertiajs/vue3` version: #.#.#
- `@inertiajs/react` version: #.#.#
- `@inertiajs/svelte` version: #.#.#

### Describe the problem:

![image](https://github.com/inertiajs/inertia/assets/4314201/9905bb14-9518-45b2-b5bf-a0f24ed5cbdc)

Error on site. 

### Steps to reproduce:

Just click on link. Add documentation issues plz =)
TYMV for the inertia!

**Comment by valh1996** [comment]
Hi @vobar

Thank you for your report. The issue is in the wrong place, it concerns the inertiajs site repository, not the library itself.

I think that if you want to make things happen, you can [submit a PR](https://github.com/inertiajs/inertiajs.com/blob/master/resources/js/Pages/scroll-management.jsx#L27) directly.
