### ISSUE TITLE
[inertia-vue] Laravel Echo  CSRF 419

### ISSUE THREAD

**Issue by sylarbg** [inertiajs/inertia#168]
Hi,

I'm using Inertia in combination with Laravel Echo. After redirecting the logged user
(session is regenerated from $request->session()->regenerate()), Echo fires a request to broadcasting/auth with the old csrf token (because it has retained the old meta tag from /login)  and result is 419 http code

Is there any way I can do hard redirect or another option tо get regenerated token  ?

Thanks!

P.S
I found this https://github.com/inertiajs/inertia-laravel/issues/57#issuecomment-531001100 as posibble solution

**Comment by reinink** [comment]
Most often folks have issues with CSRF tokens when they are using the CSRF meta tag. This will cause issues with Inertia.js, since Inertia.js does not do full page reloads...meaning if the CSRF token is updated, the value in the meta tag becomes stale. The solution is to simply remove it, since it's not needed. Laravel and Axios automatically handle this for you, which you can read more about [here](https://inertiajs.com/security#csrf-protection).

**Comment by clayzar** [comment]
@sylarbg, While I'm not using Inertia, I ran into this issue with my own Vue.js SPA when using Laravel Sanctum for my authentication guard. While Axios automatically handles this for you when using the global Axios instance.. the issue, as you stated, was that Laravel Echo did not automatically use the new CSRF token for the `broadcasting/auth` request after logging in without a full page refresh, resulting in a 419 status code.

To solve this, I manually updated the CSRF token header for Laravel Echo using the code below, right before my first attempt to subscribe to a private channel. I hope this helps you.

```javascript
// Get csrf token from cookie
const name = 'XSRF-TOKEN'
const cookies = '; ' + document.cookie
const parts = cookies.split('; ' + name + '=')
let value = parts.length == 2 ? parts.pop().split(';').shift() : null
value = decodeURIComponent(value)

// Set csrf token header for echo pusher config
Echo.connector.pusher.config.auth.headers['X-XSRF-TOKEN'] = value

// Continue as normal, subscribe to channels and events..
Echo.private('some-channel')
.listen('some-event', (e) => {
	// ...
})
```

**Comment by skeeith** [comment]
@clayzar How I usually set up my Laravel + Vue SPA, is I use the default template generated by Laravel/UI for Vue. This means my Authentication is handled by my backend (blade), while I have the full power of Vue SPA **AFTER logging in**, so I'm not having to hassle myself with access tokens (pretty neat), with this the Frontend (Vue) doesn't need an access token at all.
This also removes the hassle that you're getting right now with Laravel Echo since after I log in, I'm reloading the page with the Vue SPA on it. This loads the **XSRF-TOKEN with it**.

All my API routes are in **api.php** and all my views are in **router.js** (vue-router)
PLUS all of this is in **_one single domain_**.

All my API lives in **domain.test/api/ANY-API** and all my views live in **domain.test/ANY-VIEW**, meaning my Laravel knows if it's loading a Vue SPA or an API by know if the query string has **/api** in it, If it doesn't it has the **/api** it loads the Vue SPA.
This makes it pretty clean, very easy to maintain, scale, and develop.

the app behaves like this.
domain/users load the SPA Vue users/Index.vue
users/Index.vue does an Axios request to **domain/api/users** and then populates it.

This behaves like a **natural rest and clean** Laravel application while you have **literally the full power of Vue SPA**.

```
http://my-webapp-domain.test

CRUD      VIEW URL (VUE SPA)   METHOD      API URL

Index     /users               GET         /api/users
View      /users/1             GET         /api/users/1 (display form, view has a button for Delete and a button for Edit)
DELETE    NO VIEW API ONLY     DELETE      /api/users/1
Edit      /users/1/edit        GET         /api/users/1 (editable form, view has a button for Update)
Update    NO VIEW API ONLY     PUT/PATCH   /api/users/1
```
my **web.php** looks like this
```
// Handle Authentication
Auth::routes();

// Handle Spa
Route::get('/{any}', 'SpaController@index')->where('any', '.*')->name('index');
```
my **api.php** looks like this
```
This uses Laravel Passport or Laravel Sanctum (in your case) at the back.

Route::group(['middleware' => ['auth:api']], function () {
    // Users
    Route::match(['put', 'patch'], '/users/{user}/restore', 'UsersController@restore');
    Route::delete('/users/{user}/force-delete', 'UsersController@forceDestroy');
    Route::apiResource('users', 'UsersController');
});
```

Example **/resources/js/views/users/Index.vue** Vue file
```
<template>
    // your ui code
</template>

<script>
    export default {
        data() {
            return {
                users: []
            };
        },

        mounted() {
            axios.get('/api/users').then(res => {
                this.users = res.data.users;
            }).catch(err => {
                // handle error
            }
        }
    }
</script>
```

UsersController@index just returns a paginated json response.

All of this is just an example, in reality, my Vue files are much more complex than this handling pagination and real time search

**Comment by clayzar** [comment]
Hey @skeeith, I actually have the exact same routing setup as you. 

The front-end is mostly handled with a single route like you mentioned:
`Route::get('/{any}', 'SpaController@index')->where('any', '.*');`
API routes are tucked into their own path like `example.com/api/<endpoints>`

I was using Laravel and a typical PHP form submission to handle auth, and allow the page to reload/redirect to the SPA, which worked great. What I didn't mention is that I was looking to bring the login form in the SPA, so I could have a subtle animated transition when logging in. Sometimes the little things can turn out to be no so little 😄

**Comment by kevnk** [comment]
> The solution is to simply remove it, since it's not needed. Laravel and Axios automatically handle this for you, which you can read more about [here](https://inertiajs.com/security#csrf-protection).

Updated link: https://inertiajs.com/csrf-protection#top
