### ISSUE TITLE
Issue with multiple slots in persistence layout.

### ISSUE THREAD

**Issue by puncoz** [inertiajs/inertia#171]
I have used a persistence layout where two slots (scoped slots) are present. Now I can't use that multiple scoped slots in my pages to push content in a layout. Any workaround on this?

Here is something that I was trying to do.

```javascript
<template>
<main>
    <slot name="header"/>
    <slot/>
</main>
</template>

<script>
export default {
    name: "Layout",
}
</script>
```

and my page is something like this:
```javascript
<template>
<div>
    page content
</div>
</template>

<script>
export default {
    name: "Page",
    layout: (h, page) => h(Layout, [page])
}
</script>
```

How can I pass the content of the `header ` slot? I can do the following, as mentioned in https://github.com/inertiajs/inertia-vue/pull/87#issuecomment-536436890
```javascript
export default {
    layout: (h, page) => {
        return h(Layout, {
            scopedSlots: {
                header() {
                    return h('span', 'Header')
                }
            }}, [page])
    },
}
```

But I have not just a simple "Header" text in span. So I guess it's not that easier to write the whole content of the header in that way. 

Any suggestion what should I do?

**Comment by jamesburrow23** [comment]
@claudiodekker - Question for you....Have you used this approach to persistent layouts in conjunction with code splitting?  Today I implemented code splitting in my application but my persistent layout is no longer being rendered.

Was curious if you've seen this before

**Comment by claudiodekker** [comment]
@jamesburrow23 Hmm.. No, I haven't. Sorry.

To be honest, I've also since migrated to a different approach, at which I threw out VueX altogether.
My main reasoning for this is that Inertia was designed to have it's state managed on the back-end, and I wanted to prevent having 'two' sources of truth.

What I've decided to do instead, is to use Vue's built-in `provide` and `inject`.It's not reactive, but it solves the same issue:
- https://vuejs.org/v2/api/#provide-inject
- https://vuejs.org/v2/guide/components-edge-cases.html#Dependency-Injection

**Comment by jamesburrow23** [comment]
@claudiodekker thanks for the reply!  I've used provide and inject in various places but unfortunately, I've got this component that needs to be persistent so I'll keep hacking at it 👍 

I'll check out that other comment, thanks!

**Comment by jamesburrow23** [comment]
For anyone who stumbles across this issue, I was able to work around my issue by using this package: https://github.com/LinusBorg/portal-vue

I have `portal-target` components in my persistent layout where i'd normally use a conventional vue named slot.  Then in my inertia pages I can push my content into those portal targets using `<portal to="target-name">`

With this setup my code splitting works again since my inertia page component is invoking PersistentLayout, obviously you lose some of the vue goodness like scopedProps but most of your state should be in a vuex store anyways 😄 

here is a simple example:

![carbon (1)](https://user-images.githubusercontent.com/16297677/93272088-bd2eee00-f782-11ea-82bc-5cddd5f1dee0.png)

**Comment by msonowal** [comment]
@jamesburrow23 
So, in vue3 we have teleport but the same problem exists when using code splitting aka dynamic import the layout is not rendered, is there any solutions?

**Comment by nelson6e65** [comment]
Teleport workaround is not useful on slots with default content. It's a Vue 3 issue too.

**Comment by danielh-official** [comment]
My workaround is to use Vuex to inject the data into the app layout every time a mutation is run.

**Comment by swvjeff** [comment]
I'm also curious about this for Vue 3. I'd love to use Inertia's persistent layouts but I haven't figured out any reliable way to either a) pass data from the child component to the parent layout, or b) use scoped slots with persistent layouts. Vue-portal hasn't added Vue3 support, Vue's teleport doesn't seem like the correct solution, and I can't seem to use Vue's render function to achieve this either.

Unfortunately I'm pretty new to both Inertia and Vue, so I'm not getting anywhere. I've read and watched as many resources as I could but still haven't found an answer yet. Has anyone found a good solution?

**Comment by zamblas** [comment]
Any updates on this? 😅

**Comment by weavdale** [comment]
@reinink @claudiodekker any update? I just painfully ran into this today when trying to modify a new Breeze install.

**Comment by ordago** [comment]
@ThaDaVos I'm using teleport for the modals and slide overs without problems.

vue 3.2.37
@inertiajs/inertia 0.11.0

**Comment by ThaDaVos** [comment]
> @ThaDaVos I'm using teleport for the modals and slide overs without problems.
> 
> vue 3.2.37 @inertiajs/inertia 0.11.0

Is your Teleport target inside the Persistent Layout? Does your buildstack use Vite and uses Laravel as backend?

**Comment by ordago** [comment]
My teleport targets are in the blade base file (so, yes to Laravel). Right above `</body>`.
I'm still using Laravel Mix.

I also have a teleport target inside a component of an Inertia page, and it's also working.

**Comment by jamesburrow23** [comment]
I've kept up with this thread over the past couple of years but haven't been able to contribute lately since I haven't been on Vue 3 however now I am working on a new project using the latest version of Vue and Inertia and wanted to post my experience.

I've been able to use named slots in my persistent layouts without any problems when using code splitting.  The only caveat to that is I have to use the old `<div slot="breadcrumbs">` syntax instead of `<template #breadcrumbs>`

I am also using Vite instead of Mix which may be why I have not experienced the same problem.

I'm running an application using Laravel 8 and the legacy version of [Laravel Vite](https://legacy.laravel-vite.dev/).  I've also included the relevant files for reference if this is useful for anyone who stumbles across this thread and is looking for an idea to spark a solution for their problem. 

I was hoping I'd be able to contribute something more helpful, but all I have to offer is maybe switch to Vite if that is feasible for your situation


vite.config.js
```js
import { defineConfig } from 'laravel-vite'
import vue from '@vitejs/plugin-vue';
import Inertia from 'inertia-plugin/vite';

let config = defineConfig({
    build: {
        rollupOptions: {
            output: {
                entryFileNames: `assets/[name]-[hash].js`,
                chunkFileNames: `assets/[hash].js`,
                assetFileNames: `assets/[name]-[hash].[ext]`
            }
        }
    }
}, {
        "entrypoints": [
            "resources\/js\/app.js",
            "resources\/js\/bootstrap.js"
        ],
        "ignore_patterns": [
            "\/\\.d\\.ts$\/",
            "\/\\.json$\/",
            "\/\\.test\\.(ts|js)$\/",
            "\/\\.spec\\.(ts|js)$\/"
        ],
        "aliases": {
            "@": "resources"
        },
        "public_directory": "",
        "ping_timeout": 10,
        "ping_url": "https://app.lcl:3000",
        "build_path": "build",
        "dev_url": "https://app.lcl:3000",
        "commands": [],
    })
    .withPlugin(vue)
    .withPlugin(Inertia());

export default config;

```

app.js
```js
import { createApp, h } from 'vue';
import { createInertiaApp, Link, Head } from '@inertiajs/inertia-vue3';
import '@/css/app.css';
import PrimaryLayout from "./Shared/Layouts/Primary.vue";
import { InertiaProgress } from '@inertiajs/progress'

createInertiaApp({
    resolve: async name => {
        let page = (await import(`./Pages/${name}.vue`)).default;

        page.layout ??= PrimaryLayout;

        return page;
    },
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .component('Link', Link)
            .component('Head', Head)
            .mount(el)
    },
    title: name => `My App - ${name}`,
});

InertiaProgress.init();

```

Shared/Layouts/Primary.vue
```vue
<template>
  <main class="bg-black h-16 z-1000 sticky top-0 flex items-center justify-between px-8">
    <p class="text-center text-white">My App</p>

    <div class="flex items-center space-x-4 text-white">
      <Link href="/">Home</Link>
      <Link href="/video">Videos</Link>
    </div>
  </main>

  <slot name="breadcrumbs"></slot>

  <slot />
</template>
```

Pages/Home.vue
```vue
<template>
  <Head title="Home" />

  <div slot="breadcrumbs">
    <h1 class="text-lg font-bold m-4">Breadcrumbs</h1>
  </div>

  <div>
    <h1 class="text-lg font-bold m-4">Home</h1>
  </div>
</template>
```

**Comment by weavdale** [comment]
@jamesburrow23 thanks for posting this. I just tried this in a new Laravel 9 app (Breeze + Vue) with latest version of Vue 3. Unfortunately it's a no go. The name slot content only readers in the default slot instead of the named slot.

**Comment by jamesburrow23** [comment]
@weavdale Sorry I'm just now seeing your response.  You're not able to use named slots when using Vite and the old slot syntax like `<div slot="">`?

**Comment by javoscript** [comment]
> @weavdale Sorry I'm just now seeing your response. You're not able to use named slots when using Vite and the old slot syntax like `<div slot="">`?

@jamesburrow23, it isn't working for me either. It renders everything in the default slot. And it throws a warning about a deprecated `slot` attribute (`[vue/no-deprecated-slot-attribute] 'slot' attributes are deprecated`). Using the new syntax (something like `<div #header>Content</div>`) squaks about `[vue/valid-v-slot] Named slots must use '<template> on a custom element`...

@weavdale, I got it to work with a `<Teleport />` and waiting for the `onMounted` event on the page component.
Something like this:

In the persistent layout component:
```vue
<template>
    <div>
        <div data-slot="header" />
        <main> <slot /> </main>
    </div>
</template>
```

In the page component:
```vue
<script setup>

import { onMounted, ref } from 'vue';

const mounted = ref(false);

onMounted(() => mounted.value = true);
</script>

<template>
    <Teleport to='[data-slot="header"]' v-if="mounted">
        <h2>Title</h2>
    </Teleport>
    <div> The rest of the component... </div>
</template>
```

- The choice for using a `data-slot` custom attribute is just arbitrary... Any valid CSS selector may be used to target the "receiving" end of the `Teleport`.
- The waiting for the `onMounted` event seems to be necessary due to the order in which Inertia builds the layout and pages.

**Comment by jamesburrow23** [comment]
@javoscript It makes sense that it would throw the error about using `<div #header>` because the `#slot` syntax is only valid for the template tag. 

I'm not sure why it wouldn't work for you, the only thing I can think of like I mentioned before in my update a few weeks ago is I'm using Vite instead of webpack and I haven't had any issues.

**Comment by kurtkonijn** [comment]
@jamesburrow23 Thanks for posting, this seems to be working great! 
Now this might be a stupid question, but where te define the layout if you don't want to use the default layout setup (so not the PrimaryLayout you've configured in app.js)

**Comment by JimmyNeutron020** [comment]
Any update on this issue? 🥲

**Comment by jamesburrow23** [comment]
> @jamesburrow23 Thanks for posting, this seems to be working great! Now this might be a stupid question, but where te define the layout if you don't want to use the default layout setup (so not the PrimaryLayout you've configured in app.js)

@kurtkonijn sorry for the late reply, I would specify that in whatever page I wanted to use a different layout.  Say for example I have a custom marketing page that doesn't follow my application's default layout I can "hijack" the layout by specifying it in that component.  Something like this:
```
<template>
  <div>
    This is a my marketing page
  </div>
</template>

<script>
import Secondary from "@/js/Shared/Layouts/Secondary.vue";

export default {
  layout: Secondary,
}
</script>

```

**Comment by kurtkonijn** [comment]
> > @jamesburrow23 Thanks for posting, this seems to be working great! Now this might be a stupid question, but where te define the layout if you don't want to use the default layout setup (so not the PrimaryLayout you've configured in app.js)
> 
> @kurtkonijn sorry for the late reply, I would specify that in whatever page I wanted to use a different layout. Say for example I have a custom marketing page that doesn't follow my application's default layout I can "hijack" the layout by specifying it in that component. Something like this:
> 
> ```
> <template>
>   <div>
>     This is a my marketing page
>   </div>
> </template>
> 
> <script>
> import Secondary from "@/js/Shared/Layouts/Secondary.vue";
> 
> export default {
>   layout: Secondary,
> }
> </script>
> ```

Thanks @jamesburrow23 for the reply! 

That's not within the <script setup> part then. 
Made a workaround with a custom component based on @javoscript 's idea and using unplugin define options (https://vue-macros.sxzz.moe/macros/define-options.html)

**Comment by jamesburrow23** [comment]
> 

Nice find!

**Comment by jamiethorpe** [comment]
@jamesburrow23 I notice you're using this plugin, which doesn't seem to be mentioned in the Laravel Vite docs you linked. 
```js
import Inertia from 'inertia-plugin/vite';
```
The laravel vite docs show this config instead:
```
import { defineConfig } from 'vite'
import tailwindcss from 'tailwindcss'
import autoprefixer from 'autoprefixer'
import laravel from 'vite-plugin-laravel'
import vue from '@vitejs/plugin-vue'
import inertia from './resources/scripts/vite/inertia-layout'

export default defineConfig({
	plugins: [
		inertia(),
		vue(),
		laravel({
			postcss: [
				tailwindcss(),
				autoprefixer(),
			],
		}),
	],
})
```

Did you have to switch to using the `inertia-plugin/vite` plugin to get the named slots to work?

**Comment by jamesburrow23** [comment]
@jamiethorpe It is possible that something in that package is what makes named slots work for me, I don't know for sure to be honest.

**Comment by jamiethorpe** [comment]
> @jamiethorpe It is possible that something in that package is what makes named slots work for me, I don't know for sure to be honest.

No worries at all. I ended up just using non-persistent layouts when I need multiple slots. Thanks for posting your example either way!

**Comment by MrLanguageApp** [comment]
Isn't it strange that it doesn't say anything about this in https://inertiajs.com/pages?

When you go to implement you realize you can't use named slots?

**Does anything think there is a performance enhancement by using persistent layouts?** (it seems like not much according to vue devtools?)

defineOptions macro is mentioned, but it doesnt seem to work.

**Comment by jamiethorpe** [comment]
@MrLanguageApp I'm using defineOptions, but really just to make defining the layout cleaner. 

I'm not really sure if there's a performance improvement or not, but we've defaulted to using persistent layouts whenever we don't need multiple slots just in case.

**Comment by jamesburrow23** [comment]
@MrLanguageApp I can't speak to a quantifiable performance improvement but you can imagine the user's experience would be noticeably improved.  That "first time to meaningful paint" is going to be quicker if you're only loading what you need instead of the layout every time 🤷

**Comment by reinink** [comment]
Hey folks, just going through old issues tonight and came to this one. While I totally get why folks want this, I don't realistically see us implementing this in the foreseeable future, as this is a non-trivial problem to solve.

If you really to use multiple slots, I'd recommend just not using persistent layouts.

**Comment by tomstig** [comment]
> I'm sorry but I regard this is a serious flaw in the sustainability of Inertia.js as a whole. While I'm not opposed to digging in and figuring this out & contributing code, this issue should not be closed at the least. This is a dealbreaker feature for using Inertia in any project going forward.

I truly was flabbergasted when I started a fresh Laravel Jetstream app, thought, "Oh wait, they haven't changed it to persistent layouts yet, let's do that quickly", and when I removed AppLayout before the `<template #header>`, VS Code threw multiple errors and the website threw "Codegen node is missing for element/if/for node. Apply appropriate transforms first."

(I'm also writing this here because it took me a while until google brought me here, was too focused on "Jetstream")

**Comment by captenmasin** [comment]
I'm sure I've done something wrong but I don't even have named slots and I'm having this issue, it's quite a pain and I can't find any resources on it

**Comment by captenmasin** [comment]
Weirdly enough it works fine if I replace

page.default.layout = page.default.layout || BaseLayout

With
```
page.default.layout = page.default.layout || ((h, p) => h(BaseLayout, {}, [p]))
```

**Comment by aeruggiero** [comment]
Did someone found a workaround?
This is really bugging me!
I think that persistent layout is the best solution for a SPA but without the possibility to use named slots it's really frustating to use it.

**Comment by vitalijalbu** [comment]
Also having this issue on react

**Comment by Bosphoramus** [comment]
😕

**Comment by aarondfrancis** [comment]
Just came across this again. I would love for this to be reconsidered.

**Comment by Bosphoramus** [comment]
In the end i ended up not using persistent layouts, as i didnt really need them

I did not want to persist any state between page visits, and by not using persistent layouts i now have the possibility of using named slots, and Ziggy directly for link active states, as the route() function gets re-run in every page transition

Of course this is still a problem for people that need to preserve state between page visits like a video or audio player in the layout, but if you dont strictly need it, i wouldnt use persistent layouts

**Comment by JimmyNeutron020** [comment]
I encountered this issue on a project a few years ago. I recommend making your Laravel application headless and using a framework like Next or Nuxt for the frontend. While it may seem like a lot of initial setup, including endpoints and authentication, it will save you time and reduce headaches in the long run.

InertiaJS is a great concept, but in practice, I found it to be less flexible and too intertwined with the backend, often requiring many workarounds. Separating the backend and frontend is the best practice in my opinion.

**Comment by lbattaglioli2000** [comment]
Yeah I'm running into this same issue too, any sort of workaround would be lovely.

**Comment by aeruggiero** [comment]
> Yeah I'm running into this same issue too, any sort of workaround would be lovely.

As for now, the best way to solve it is using @javoscript solution, combined with multiple persistent layout. (defineOptions({layout:[layout_a,layout_b,etc.]})

**Comment by lbattaglioli2000** [comment]
Yeah that's what we ultimately ended up doing too. 

We have a root AppLayout, and specific sub-layouts we nest. Those sub layouts don't use the named props, and just have the components we need already in there. If we need to hide or remove something, we'll just have to use another nested layout.
