### ISSUE TITLE
Multiple of the same url in browser history

### ISSUE THREAD

**Issue by JonasCykelgear** [inertiajs/inertia#1712]
### Version:

- `@inertiajs/vue3` version: 1.0.9

### Describe the problem:

We have 4 websites running the same codebase, on one of those websites it seems that inertia adds entries to the browser history on every navigation request.

If i click a link on the site, the target site gets added twice to the browser history, which makes me unable to go back using the back button.

### Steps to reproduce:

I cant reproduce this on other site or locally. How ever it happens 100% of the times on our live website. (https://bikable.no)

Let me know more info is needed

**Comment by craigrileyuk** [comment]
This seems to be an implementation issue rather than an Inertia problem.

If you notice, the double-history entry only seems to happen when navigating to categories. If you use your links in the page footer or, for example, your [Pages](https://bikable.no/kundeservice) section, it's working correctly.

I would check for an errant `router.reload` in your category layout/page or something else that's triggering a reload.

**Comment by JonasCykelgear** [comment]
> This seems to be an implementation issue rather than an Inertia problem.
> 
> If you notice, the double-history entry only seems to happen when navigating to categories. If you use your links in the page footer or, for example, your [Pages](https://bikable.no/kundeservice) section, it's working correctly.
> 
> I would check for an errant `router.reload` in your category layout/page or something else that's triggering a reload.

I figured it would be an implementation issue. What is weird to me is that it only happens on our norwegian site.
We also have bikable.com and bikable.se where this issue doesnt happen.

Also, for me it happens on footer links and pages aswell.

**Comment by craigrileyuk** [comment]
![Screenshot 2023-10-27 at 08 14 37](https://github.com/inertiajs/inertia/assets/68274157/719b34a1-38d3-4507-b485-a513b57f768e)

There seems to be a lot going on during an Inertia navigation to a new page (ignore the blocked call to zendesk, my adblock stops that from going through).

Basically, you're landing on the page (the first Inertia GET request).

Then there's a call to `filters` that's being blocked. This is usually because you're attempting to do multiple Inertia `router` calls at the same time each new request will cancel any previous incomplete calls.

Then you're immediately reloading the first page of product results (`page=1&products_per_page=30`). **This is almost certainly the step that is giving you multiple history entries**.

Then there's another POST request going up to products.

All before I've touched a single thing after loading.

**Comment by JonasCykelgear** [comment]
> ![Screenshot 2023-10-27 at 08 14 37](https://user-images.githubusercontent.com/68274157/278565370-719b34a1-38d3-4507-b485-a513b57f768e.png)
> 
> There seems to be a lot going on during an Inertia navigation to a new page (ignore the blocked call to zendesk, my adblock stops that from going through).
> 
> Basically, you're landing on the page (the first Inertia GET request).
> 
> Then there's a call to `filters` that's being blocked. This is usually because you're attempting to do multiple Inertia `router` calls at the same time where each new request will cancel any previous incomplete calls.
> 
> Then you're immediately reloading the first page of product results (`page=1&products_per_page=30`). **This is almost certainly the step that is giving you multiple history entries**.
> 
> Then there's another Ajax POST request going up to products which seems to return the product data as a completely different request stream...
> 
> All before I've touched a single thing after loading.

Yeah i see what you mean.

We are loading the products and filters after the page is switched, thats why it does that. Maybe thats stupid?

Ill look into those extra calls. Thanks for the help :)

**Comment by reinink** [comment]
Hey going to close this one because I don't think it's actually a bug with Inertia.js but rather just a problem with you particular implementation. If you need further help I'd recommend asking it in our [discussions](https://github.com/inertiajs/inertia/discussions) or on Discord. Good luck! 👍

**Comment by JonasCykelgear** [comment]
[like]  Jonas Rasmussen reacted to your message:
________________________________

**Comment by boutzamat** [comment]
Sorry to necro, but i'm experiencing the exact same thing. 
However i posted my issue in the Inertia-Laravel repo as i thought it was related to Laravel (somehow) but i doubt it.
I'm elaborating a bit more on my issue, with screenshots too.

https://github.com/inertiajs/inertia-laravel/issues/583
