### ISSUE TITLE
[inertia-vue] `remember` does not work with `Object.assign`

### ISSUE THREAD

**Issue by robsontenorio** [inertiajs/inertia#173]
Yes, this works.

```js
export default {
  props: ["user"],
  remember: "form",
  data() {
    return {
      form: {
         name: this.user.name
         age: this.user.age
         ...
      }
    }
  }
}
```

But, it is a bit boring describe all fields on `form` objet. So inestead i usually do this:

```js
export default {
  props: ["user"],
  remember: "form",
  data() {
    return {
      form: { }
    }
  },
  beforeMount() {
     this.form = Object.assign({}, this.user);
   }
}
```
But i just noticed the fields won`t be remembered.

**Comment by claudiodekker** [comment]
Hi,

Here's what's most likely happening. Let me know if I'm wrong:

1. Inertia and Vue are booted. 
2. As per the [Vue lifecycle](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram), [Inertia's state-remembering mechanism](https://github.com/inertiajs/inertia/blob/d2e055a93462bd919265b4abb4edef4b31887b98/packages/inertia-vue/src/remember.js) runs
3. Inertia's remember function sees you want to remember the `"form"` key
4. Inertia's remember function checks whether there is data that was remembered from earlier, and if there is, [it restores it by updating the component](https://github.com/inertiajs/inertia/blob/d2e055a93462bd919265b4abb4edef4b31887b98/packages/inertia-vue/src/remember.js#L29).
5. Inertia's remember function [watches the `"form"` key, and](https://github.com/inertiajs/inertia/blob/d2e055a93462bd919265b4abb4edef4b31887b98/packages/inertia-vue/src/remember.js#L32) 'remembers' (stores) them once it detects changes
6. As per the [Vue lifecycle](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram), your `beforeMount` function gets called, which assigns the user data (from the component's prop) to the `"form"` data key.
7. Inertia's remember watcher (see step 5) gets triggered, which then stores the data you just wrote, overwriting existing values for those same keys.

On the next page reload/component instantiation, the cycle repeats itself. 

**Now, as for the issue itself**: On step 4, your existing user data gets loaded correctly, but by the time it reaches step 6, the data is overwritten. The likely reason as to why this happens, is because on the second page load or initialization, your `this.user` prop might not have data, resulting in that empty object being assigned. Then, as per step 7, your (correctly-stored) user data gets overwritten with these empty values.

What you'll probably want to do, is to add a check (in your `beforeMount`) whether there is a non-empty user object, and to only set it (the way you're doing it is fine) if it is there. This way, everything should work, even cross-reload:
```js
export default {
  props: ["user"],
  remember: "form",
  data() {
    return {
      form: { }
    }
  },
  beforeMount() {
     if (this.user && Object.keys(this.user).length > 0) {
       this.form = Object.assign({}, this.user);
      }
   }
}
```

Hope it helps!

**Comment by reinink** [comment]
Thanks for your help here @claudiodekker. 👍
