### ISSUE TITLE
CRITICAL: SSR Slows down website after a few seconds and after that response is not containing server side content

### ISSUE THREAD

**Issue by MohammadZarifiyan** [inertiajs/inertia#1730]
#### package.json:
- `@inertiajs/vue3` version: 1.0.14
- `vite` version: 4.5.0
- `@vitejs/plugin-vue`: 4.4.0
- `laravel-vite-plugin`: 0.8.1

#### composer.json
- `inertiajs/inertia-laravel`: 0.6.8
- `laravel/framework`: 9.24

### Describe the problem:

Hello. SSR in InertiaJS has a problem. There is no error. There is no crazy code. Just a normal project. When I run node `bootstrap/ssr/ssr.js` the SSR works fine. But after a few minutes and receiving several requests, SSR slows down and loading the page takes more than 20 seconds, and after 20 seconds the content of the page is displayed without server side rendered content. While `ssr.js` is still running and there is no error in the console.
All i see is this:
`Starting SSR server on port 13714...
Inertia SSR server started.`

I tried multiple node versions (v16/v18) and removed `node_modules` & `public/build` & `bootstrap/ssr` folders and ran `yarn && yarn run build` several times but absolutely no change happend.

**Comment by y1ann1s85** [comment]
@MohammadZarifiyan Did you find out what the problem was?

**Comment by marcbelletre** [comment]
I'm also curious @MohammadZarifiyan. I have the exact same problem and can't figure out why. Since you marked the issue as completed I assume you found a solution? In that case would you have the kindness to share it with us? :)

**Comment by y1ann1s85** [comment]
@marcbelletre Did you see any other issues opened related to this? I thought I was the only one facing it apart from @MohammadZarifiyan who seems to have abandoned the current issue. I didn't manage to find anything relative. And it is hard to make a reproduction link of it as an example. I had to benchmark our servers with thousands of requests in order to reproduce it on a staging level and try and debug it.

**Comment by marcbelletre** [comment]
@y1ann1s85 I only found one question on Stackoverflow that did not get any answer [here](https://stackoverflow.com/questions/76771155/laravel-inertiajs-website-too-slow-with-ssr-server-side-rendering).  

I have two sites that use Inertia with SSR and I recently noticed huge performance issues on the first one I built. As soon as I stopped the SSR the website was loading fast again so I re-started it but the problem came back the day after. It looks like it's getting slower each day.  

I don't have the problem on the second site I built last year so I don't think this is related to Inertia itself.  

I'm still investigating. I will tell you if I find anything!

**Comment by y1ann1s85** [comment]
@marcbelletre Pretty much the same here as well. Still trying to figure out what is causing the SSR to slow down. If we perform a restart on the server's ssr daemon everything comes back to normal. Thanks in advance @marcbelletre . If we find something as well I' ll let you know.
