### ISSUE TITLE
Link not working in new @inertiajs/react application.

### ISSUE THREAD

**Issue by cdmorris** [inertiajs/inertia#1742]
### Version:

- `@inertiajs/react` version: 1.0.14

### Describe the problem:

The following link on a page 
```
<Link as="button" type="button" href= "/customeradmin" >Test</Link>
```
Produces the following exception when clicked
```
router.ts:342 Uncaught TypeError: (0 , j.default) is not a function
    at G.visit (router.ts:342:5)
    at Link.ts:76:18
    at Object.eJ (react-dom.production.min.js:54:317)
    at e3 (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at rp (react-dom.production.min.js:55:136)
    at rh (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at l$ (react-dom.production.min.js:274:42)
    at eQ (react-dom.production.min.js:52:375)
```

Calling axios.get, does work as expected.

I am using parceljs bundler.
I have the following index.tsx file
```
import React from 'react';
import { createInertiaApp } from '@inertiajs/react'
import { createRoot } from 'react-dom/client'
//@ts-ignore
import * as pages from './Pages/*';



createInertiaApp({
  resolve: name => {
    console.log('p');
      let p=pages[`${name}.tsx`];
      console.log(p);
      return p;
  },
  setup({ el, App, props }) {
    createRoot(el).render(<App {...props} />)
  },
})

``` 

Rendering first screen is otherwise perfect.

**Comment by hiddenLadder** [comment]
"as="button" type="button"" is redundant

**Comment by cdmorris** [comment]
thanks @hiddenLadder ,  I have tried just rendering a standard anchor
```
<Link href= "/customeradmin" >Test</Link>
```
it still gives me the Type Error shown above.

**Comment by RobertBoes** [comment]
It's kind of difficult to see where the error is coming from, but since it complains about `.default` I'd assume it's when the page is swapped. Are you sure the component does exist and your `resolve` method works properly? Think you might be able to test that by visiting `/customeradmin` in your browser directly. If it gives the same error the page component probably can't be found. If it works fine then it's probably something else and it might be helpful to have steps to reproduce the error (like a reproduction repo)

**Comment by cdmorris** [comment]
I came to the conclusion this was a module linking issue so I swithed from Parcel to Vite.  With no other changes it now works.

**Comment by cdmorris** [comment]
I came to the conclusion this was a module linking issue so I swithed from Parcel to Vite.  With no other changes it now works.
