### ISSUE TITLE
SSR and web components

### ISSUE THREAD

**Issue by travisricks** [inertiajs/inertia#1769]
### Versions:

- `@inertiajs/vue3` version: 1.0.14

### Describe the problem:

We have a custom element that is imported through a package. When running SSR locally, no errors were triggered, but on the production server this error was logged in Sentry:

`[Vue warn]: Failed to resolve component: cookie-consent`

We tried solving this by adding the same import statement to ssr.js that we had in inertia.js:
`import '@company-name/web-components/web-components.mjs';`

But now we're getting a new error from Sentry:
`ReferenceError: customElements is not defined`

The custom element is still working as expected on the page, but we would like to resolve these errors.

What's the best way to handle having a web custom element and using SSR?

**Comment by craigrileyuk** [comment]
`customElements` is a browser API and not available in NodeJS (in which your SSR code is executed).

You're still seeing the component because when client-side hydration executes on the browser, it _does_ have access to the customElements API and so replaces the null output provided by the SSR with the desired component.

However, Sentry, which is logging errors from your server rendering process is logging the error before it is recovered from.

As for a solution, you need to polyfill the Custom Elements API onto your SSR process. You could use a package like `happy-dom` and then place the CustomElements class on your `globalThis` in your ssr.js file.
