### ISSUE TITLE
How to Async Request in Inertia JS using React AsyncSelect

### ISSUE THREAD

**Issue by ThinkDevStudios** [inertiajs/inertia#184]
Hi! How would you request data to Inertia JS from React AsyncSelect

```js
<AsyncSelect
   cacheOptions
   defaultOptions
   placeholder="Select a Provider"
   name="make_id"
   onInputChange={e => handleProviders(e)}
   className="mt-1"
  loadOptions={getOptions}
/>
```

Should this be Inertia.visit or Inertia.post

```js
const getOptions = (input) => {
Inertia.post(
    route('providers.get'),
    input
).then((response) => {
    console.log(response); <-- need to get response here to populate options on the select input

}).catch(function (error) {
    console.log(error);
});
}
```

The AsyncSelect input is loaded from a modal. Not the actual page.
if i return an array the response cant catch it.

**Comment by reinink** [comment]
So, using the new [event callbacks](https://inertiajs.com/manual-visits#event-callbacks) in Inertia 0.3.0, you can get this response data:

```js
Inertia.post('/users', data, {
  onSuccess: page => {
    console.log(page.props) // access page props from server
  }
})
```

I'm not sure how the `AsyncSelect` component works, but if you're able to get the data via the `onSuccess()` callback and pass it to the `AsyncSelect` component, you should be good.

Alternatively, simply get this data via an xhr/fetch request, instead of using an Inertia request to get this data.

Hope that helps! 👍
