### ISSUE TITLE
[inertia-vue] Splitting a big application into multiple packages how to handle pages?

### ISSUE THREAD

**Issue by iamniels** [inertiajs/inertia#188]
I'm building a big laravel application which will be split into multiple Laravel packages. Each package will supply it's own pages. So my pages are located somewhere in the project or in a `vendor` folder. They are not nicely together in one root folder. How can I make this work?

My current idea is to add a function to `webpack.mix.js` to search for pages in folders of the packages and to extend the Inertia::render function such that it will automatically point to the correct page for packages. What do you think?

**Comment by claudiodekker** [comment]
Hi,

Personally, what I would do in this situation, is to leave Inertia's defaults as-is, but to add the `resources/js/Pages` folder to your `.gitignore`. 

Then, from there, in each of your packages, I would publish the Inertia views to your `resources/js/Pages` folder, so that they're all 'gathered' into one place by Laravel. [You can do this in your Package's Service Provider](https://laravel.com/docs/7.x/packages#configuration):
```php
/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    $this->publishes([
        __DIR__.'/path/to/views' => resource_path('js/Pages'),
    ], 'inertia');
}
```

Finally, we'll probably want to make sure that each time you run a composer command (install or update), the correct views are published. This is also fairly easy, by simply adding one line to our application's `composer.json` file:
```diff
     "scripts": {
         "post-autoload-dump": [
             "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
             "@php artisan package:discover --ansi",
+            "@php artisan vendor:publish --tag=inertia --force"
         ],
```

Your views should now automatically be 'installed' into your application whenever you update or install your packages.

Hope this helps!

**Comment by iamniels** [comment]
That is a great idea, thanks!

How would you handle Pages which are packed in NPM packages?

**Comment by reinink** [comment]
@claudiodekker Great solution if you're using Composer!

However, if you're using NPM packages, I'd take a look at the `resolveComponent` callback. This callback allows you to map the page name (as provided by Inertia during the request) to whatever component you want.

For example, you could append pages supplied by your NPM packages with an identifier:

```php
return Inertia::render('@PackageName::Event/Show');
```

And then within your `resolveComponent` callback you can parse this page name, and then modify the require. Maybe if there is `@PackageName::` present, that could refer to an NPM package page components, but if it's omitted, you could just fallback to the app page components. Something like this:

```js
new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent(name) {
        if (name.startsWith('@PackageName::')) {
          return // some NPM require
        } else {
          return require(`./Pages/${name}`).default
        }
      },
    },
  }),
}).$mount(app)
```

Does that help?

**Comment by iamniels** [comment]
Answered within 20 minutes :100: Thanks, this helps a lot!

**Comment by ycs77** [comment]
https://github.com/inertiajs/inertia-laravel/issues/92

**Comment by reinink** [comment]
@iamniels You're quite welcome! 🤟

**Comment by iamniels** [comment]
@reinink How would you handle the layout? So I would like that the `main` application forces the use of a layout on pages of the packages.

**Comment by claudiodekker** [comment]
@iamniels This, you could also do in the `resolveComponent` method. I personally do something like this in a few of my apps:

```js
resolveComponent: name => {
    const componentOptions = require(`./Pages/${name}`).default;
    componentOptions.layout = (h, page) => h(MyPersistentLayout, [page]);

    return componentOptions;
}
```

**Comment by reinink** [comment]
@claudiodekker Dig it, nice solution! 👍

**Comment by iamniels** [comment]
Thanks! @claudiodekker

**Comment by ycs77** [comment]
OK. I think I got the best solution for this issue. Thanks all for the ideas in https://github.com/inertiajs/inertia-laravel/issues/92, inspired me to create a plugin.

---

### [Inertia Plugin](https://github.com/ycs77/inertia-plugin)

> **Warning**: This plugin status is experimental, don't use it for the production application.

The plugin page loader for Inertia.js, powered by **unplugin**, supports **Vite** and **Laravel Mix**.

Define the namespace mapping for plugins pages directory, also can be extract namespace from the npm / composer plugin:

```js
// webpack.mix.js
const inertiaPlugin = require('inertia-plugin/webpack').default

mix
  .webpackConfig({
    plugins: [
      inertiaPlugin({
        namespaces: ({ npm, composer }) => [
          // define namespace mapping:
          { MyPackage1: 'node_modules/my-plugin1/src/Pages' },

          // load namespace from npm package:
          npm('my-plugin2'),

          // load namespace from composer package:
          composer('ycs77/my-php-package'),
        ],
      }),
    ],
  })
```

The npm package like `node_modules/my-plugin2/package.json`:

```json
{
  "name": "my-plugin2",
  "inertia": {
    "MyPackage2": "src/other-pages"
  }
}
```

The composer package like `vendor/ycs77/my-php-package/composer.json`:

```json
{
    "name": "ycs77/my-php-package",
    "extra": {
        "inertia": {
            "MyPhpPackage": "resources/js/Pages"
        }
    }
}
```

Will can be used namespace prefix get the view:

```php
Inertia::render('MyPackage1::Page3');
Inertia::render('MyPackage2::Page222');
Inertia::render('MyPhpPackage::PhpPackagePage');
```

For full usage see the [docs](https://github.com/ycs77/inertia-plugin).

Try it~ 😊

**Comment by craigrileyuk** [comment]
So this is something we've had to do for one of our applications.

We basically have an admin dashboard thing that controls some backend functionality that is released as a composer package.

However, when installing the package into a standard Laravel app, there is often a need to add a few extra pages custom to that application.

We've got it mostly working by having the package place a function on the window object that can be called to register pages under a namespace from an `import.meta.glob` in the frontend application.

The only problem with this is that when using Composition API, it severs the application addon pages from the backend main app in that you can't use `usePage` or `getCurrentInstance` or `provide` or `inject` because the imports resolve to a different place than the main app.

It still works if you use `$page.props` in the template or `this` inside an Options API addon page, but obviously this isn't exactly ideal.

Does anyone know how we could do about fixing this issue?
