### ISSUE TITLE
Is there a path to a native app?

### ISSUE THREAD

**Issue by justageek** [inertiajs/inertia#196]
Hi, I was curious, with Inertia and VueJS is there a path to a native mobile application at all?

**Comment by reinink** [comment]
Hey @justageek! No, there is no native mobile story for Inertia.js yet, and I'm not sure there ever will be to be honest.

For what it's worth, for my SaaS app I use Inertia.js for my web app, and then I have a light REST API for my native apps, which I built in React Native. The REST API is quite simple, since my native apps only support a small subset of the web app features—the ones that really make sense in the mobile app.

Thanks for asking, and for your interest in Inertia.js.

**Comment by reinink** [comment]
I have no idea to be honest, Inertia wasn't designed to support both use-cases, and I've never used it that way. For my Inertia apps, I create separate routes and controllers for my API endpoints (when I have them...doesn't happen often).
