### ISSUE TITLE
Can't command + click Inertia links to open them in a new tab

### ISSUE THREAD

**Issue by joelstein** [inertiajs/inertia#2127]
### Version:

- `@inertiajs/react` version: 1.3.0-beta.2

### Describe the problem:

I can't cmd + click Inertia links to open them in a new tab. They behave as though I did a normal click.

**Comment by RobertBoes** [comment]
This might be introduced in #1908 or #1910, since it does work in 1.2.0. Do you think this could've caused it @derrickreimer ?

**Comment by derrickreimer** [comment]
Ah man, I think spot the issue 🤦 I'm really surprised this didn't get caught when we were working on the prior fix.

The issue: we switched to relying solely on `event.nativeEvent` in the logic that checks whether Inertia ought to intercept an click, rather than React's synthetic event (because among other things, React was not copying properties like `button` to it's own event representation and it seemed more correct for the shared logic to be framework agnostic anyhow). 

But upon closer inspection, I'm observing that `event.nativeEvent.currentTarget` is consistently set to the React root node, whereas `event.currentTarget` on the synthetic event is the actual node that was clicked. I can submit a PR.

**Comment by reinink** [comment]
They thanks for sharing, this has been fixed in #2132 👍
