### ISSUE TITLE
I can't add transition after change page with inertia in vue js

### ISSUE THREAD

**Issue by toolekco** [inertiajs/inertia#227]
The transition Does not work in inertia page . if add appLayout between transition tag . its working . but all content gives transition

**Comment by claudiodekker** [comment]
Hi @toolekco,

This is most likely because you're using regular layouts, and not [persistent layouts](https://inertiajs.com/pages#persistent-layouts).

With regular layouts, the layout is really rendered as a 'child' component of your page, with the 'slot' content of it being your 'page content'. Basically, this means your rendering 'tree' would look like something like this:

<img width="267" alt="Screenshot 2020-09-21 at 23 00 49" src="https://user-images.githubusercontent.com/1752195/93821050-4d2ad700-fc5e-11ea-9fe7-8ce867d93abd.png">

As a result, whenever your page changes, it actually also swaps out the layout, with the result being that your transition is discarded. If you were to use [persistent layouts](https://inertiajs.com/pages#persistent-layouts) instead, your page would become a 'child' of the layout, meaning your render tree would look something like this:

<img width="405" alt="Screenshot 2020-09-21 at 23 05 43" src="https://user-images.githubusercontent.com/1752195/93821543-fd004480-fc5e-11ea-959c-78083c4a1f5c.png">

In this situation, as long as the page you're transitioning to is using the same layout, your transition should work, as the 'Layout' component will remain mounted (hence the name 'persistent layout').

Hope this helps!

**Comment by claudiodekker** [comment]
Hi, since there's been no further activity on this issue, I'm assuming this probably solved your problem and this issue can be closed. If not, feel free to re-open it!
