### ISSUE TITLE
Make `headers` available in `start` event

### ISSUE THREAD

**Issue by niveshsaharan** [inertiajs/inertia#242]
Is it possible to make `headers` object available if it is not passed while making the request? Cause If it is not passed, we cannot intercept it and add headers to a request.

```javascript
let visit = { url, ...arguments[1] }
f (onStart(visit) === false || !this.fireEvent('start', { cancelable: true, detail: { visit } } )) {
return
}
```

The solution can be as simple as:

```javascript
let visit = { url, headers: {}, ...arguments[1] }
if (onStart(visit) === false || !this.fireEvent('start', { cancelable: true, detail: { visit } } )) {
    return
}
```

I'm happy to make a pull request if that helps.

**Comment by reinink** [comment]
@niveshsaharan I don't want to sound rude here, but I am not willing to help you with your Inertia.js issues (or [PRs](https://github.com/inertiajs/inertia/pull/222)) until **you make things right with respect to my course content**.

After I gave you a MASSIVE 90% discount off my Eloquent Performance Patterns course, you proceeded to take my paid content and put it on your website. Literally 20 blog posts of MY paid content!

![image](https://user-images.githubusercontent.com/882133/94833245-e71c1d80-03dc-11eb-8c74-b5fb89faf47d.png)

I have repeatedly asked you politely remove this content from your website, but you never respond.

![image](https://user-images.githubusercontent.com/882133/94833500-2fd3d680-03dd-11eb-9ac2-e1ef2a8829cf.png)

You have, however, blocked me on Twitter, instead of responding to my requests:

![image](https://user-images.githubusercontent.com/882133/94833592-4ed26880-03dd-11eb-87a5-443b20a501ed.png)

I've even gone as far as asking Vercel to remove the content, which they did, but then you simply moved your hosting elsewhere. Even the https://dev.to moderators realized this was wrong, and remove this content (that you posted to your account) from their website

@niveshsaharan Do the right thing. Take down my content.

**Comment by niveshsaharan** [comment]
Thank you @reinink 

I understand that I can get the headers with that. However the issue is they are only available when I actually send them with the request. Let me try to explain here: 

```javascript
Inertia.visit('/home', { headers: {}}
`

```javascript
Inertia.on('start', event => {
    event.detail.visit.headers.MyCustomHeader = "header-value"
});
```

This would work just fine. But if do the following:

```javascript
Inertia.visit('/home', { }
```

```javascript
Inertia.on('start', event => {
    event.detail.visit.headers.MyCustomHeader = "header-value"
});
```

Now `MyCustomHeader` is no longer sent with the request.

**Comment by niveshsaharan** [comment]
Changing:

```javascript
let visit = { url, ...arguments[1] }
```

into this:

```javascript
let visit = { url, headers, ...arguments[1] }
```

fixes the issue. I have tested it in a clone.

**Comment by reinink** [comment]
Ahh yes, understood. So, you're basically trying to use the event system to set a global custom header. That isn't going to be possible with the event system, since event details are not (intentionally) mutable. I was considering this at first, but decided against it. See that discussion [here](https://twitter.com/reinink/status/1304007701664616448).

A bit of a hack, but a workaround to this is to cancel the event, and then fire a new visit. Untested, but something like this:

```js
Inertia.on('start', event => {
  // prevent the event
  if (event.detail.visit.headers.MyCustomHeader === undefined) {
    event.preventDefault()
  }

  // do new visit instead
  Inertia.visit(event.detail.visit.url, {
    ...event.detail.visit,
    headers: {
      MyCustomHeader: 'header-value',
    }
  })
})
```

It might also make sense to add a default custom headers option to Inertia at some point.

**Comment by niveshsaharan** [comment]
Thank you for your response.
