### ISSUE TITLE
$inertia is undefined when using Jest

### ISSUE THREAD

**Issue by mrpritchett** [inertiajs/inertia#246]
I receive this error when I'm testing a vue component that uses inertia to send a request from a form.
`
TypeError: Cannot read property 'form' of undefined`

`
mounted() {
  this.form = this.$inertia.form({...stuff here...})
`

What's the right way to either mock or include $inertia so it is usable in something like Jest for testing components?

**Comment by mrpritchett** [comment]
I ended up going a bit crazy with dependencies which doesn't feel like the right solution, but this worked for me:

```
import Vue from 'vue'

import { mount } from '@vue/test-utils'
import { InertiaApp } from '@inertiajs/inertia-vue'
import { InertiaForm } from 'laravel-jetstream'
import Create from './../../Pages/Space/Create.vue'

Vue.use(InertiaApp);
Vue.use(InertiaForm);

test('should mount without crashing', () => {
    const wrapper = mount(Create)

    expect(wrapper).toMatchSnapshot()
})

```

**Comment by claudiodekker** [comment]
Hi,

Yes, your solution is indeed the correct one. The reason for this is that `$inertia.form` is not actually something baked-in and provided by Inertia, but rather a third-party plugin by the Laravel Jetstream team that hooks into the core of Inertia's `$inertia` plugin.

Because this means that `$inertia.form` depends on `$inertia`, you indeed have to register both, like you already figured to be the case.

**Comment by reinink** [comment]
Thanks for helping out here @claudiodekker. 👍

**Comment by mrpritchett** [comment]
Awesome. Thanks, @claudiodekker & @reinink. I really appreciate the time to confirm my understanding and explain why it works. That says a lot about this package and community that you would do so instead of just closing the issue as "not our problem." ❤️
