### ISSUE TITLE
Respect client errors in event callbacks

### ISSUE THREAD

**Issue by ajnsn** [inertiajs/inertia#252]
When trying to submit a form, there will be most likely client errors, e.g. validation errors (422), throttling errors (429 etc.
Inertia does always return a 200 response which makes it somehow difficult to properly respond to these errors. 

It would be good to have this new event system keep to "internal" response state somewhere. Besides the underlying request, e.g. the onSucess callback could maybe only fire when there are no client errors?

In the code example is a simple post request to track a time entry. When the user sucessfully submits a time entry, the form should reset to allow the user to submit another time entry. I need to check for errors (!this.errors.any()) inside the onSuccess callback to determine if there are any errors and then reset the form. 

Is there any other way to achieve this?

```javascript
this.$inertia.post(this.$helpers.route('time-entries.store'), this.form.data, {
    preserveScroll: true,
    onStart: visit => {
        this.errors.clear();
    },
    onSuccess: page => {
        if (!this.errors.any()) {
            this.form.reset();
        }
    },
});
```

**Comment by SimplyCorey** [comment]
I have similar feedback.  I was using the `onSuccess` callback and was quite confused when a JSON validation error was making it into this callback.  Maybe an `onFailure` callback is needed? 

```
this.$inertia.post(route(....)), this.form.data, {
    onFailure: visit => {
        //validation errors or other network errors.
    },
    onSuccess: page => {
        //Only called when no validation errors happen
    },
});
```

**Comment by reinink** [comment]
So, I think I need to write a blog post or do a quick screencast on this, because this seems to trip people up. I'll do my best to explain why Inertia works this way.

Quite often folks coming to Inertia for the first time think of it as a replacement for manual XHR/fetch requests, where you submit a request, and then inspect the response, and handle the success and failure states. That isn't actually the case. A better comparison for Inertia is classic full-page visits and form submissions.

For example, in a classic server rendered application, when you submit a form, the `store()` endpoint runs some validation, creates a record, and then **redirects** to a different page on success. In fact, in validation fails, it also performs a redirect back to the page (form) that submitted the request (so you can show the validation errors and repopulate the form new input values).

Inertia works the same way. And, at first, this feels different/odd, but once you get used to it, it's actually quite awesome.

Let's take a closer look at validation errors. When validation errors occur, Inertia doesn't see a 422 response code, because a 422 was never sent back to the browser. Rather, when the validation errors occurred, a redirect occurred server-side back to the form page, passing through the validation errors as session (flash) data, which then gets shared to the client-side (Inertia) as props.

The really cool thing here is that when Inertia receives a response back to the same (form) page, with updated (error) props, your error messages automatically appear, since props are reactive. I never "clear" my validation errors, since this just happens automatically.

Basically, don't think of `onSuccess()` as "no validation errors occurred", but rather think of `onSuccess()` as "a successful 200 Inertia response was received". And remember, a 200 response may have occurred as a result of validation errors.

As for the form reset "problem", checking the `errors` prop is exactly how you do this. You can see that [we do this](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Edit.vue#L90-L94) in the Ping CRM source code.

Again, I admit that this feels odd at first, but practically, building forms this way is actually awesome. A big goal of mine with Inertia is to not have to manually deal with all the possible 400/500 level error responses when you submit an Inertia response. Rather, these should be (almost always) be handled globally in your Inertia app. Be sure to see the [error handling](https://inertiajs.com/error-handling) page in the documentation for good explanation of how that's done. The only real exception is 422 validation responses, which contain errors that need to be displayed to the user. Frameworks like Laravel already automatically handle this situation differently, by redirecting back to the previous page with errors as flash data. You can find documentation about how to handle validation errors in the docs [here](https://inertiajs.com/forms#server-side-validation).

I recently [gave a talk on Inertia](https://vimeo.com/467095891), and I spend a bunch of time on forms. You might find that helpful. 👍

**Comment by SimplyCorey** [comment]
@reinink Thanks for the detailed explanation.  So far, I have really enjoyed using the Inertia in a project.  Just for a point of clarity, I have the following code in my project for a save method.  Would you consider this to be the "correct way" of dealing with validation errors?  Basically, I'm checking to see if the error prop has any errors and if not closing the menu.  Hopefully, some others find some use in this demo code as well.

```
    async save() {
      const callback = {
        onSuccess: (page) => {
          if (isEmpty(page.props.errors)) {
            this.closeMenu();
          }
        },
      };

      if (this.menu.bucket.id) {
        await this.$inertia.put(this.route('buckets.update', this.menu.bucket), this.menu.bucket, callback);
        return;
      }

      await this.$inertia.post(this.route('buckets.store'), this.menu.bucket, callback);
    },
```

**Comment by claudiodekker** [comment]
In addition to @reinink's detailed post above, I'd like to add the following:

Traditionally, the 'glue' between the browser/client and the server is the HTTP layer, where if you really think about it the 'status code' is just something that's part of the request's metadata. 

However, when you work with Inertia, you don't directly interface with the HTTP layer anymore. This is because Inertia has both a front-end wrapper, as well as a back-end wrapper that encapsulate this entire layer. As a result, the HTTP status code (and many other HTTP metadata details) become irrelevant to whether the request actually succeeded. 

---

Of course, I realize that while this answers your question, it doesn't solve your problem(s), so let's go through an example of a situation you outlined above: Throttling. 

Let's say a HTTP 429 "Too Many Requests" situation happens. Because Inertia always expects an Inertia response, what we want to do is to prevent this response from being sent in the traditional way, and instead render it as an Inertia response instead that can then be used on our front-end, so we don't run into odd errors. 

So, how do we go about this? Let's say we're using Laravel. What causes the HTTP 429 "Too Many Requests" response to be sent? Well, if we dig into the code, we can see the `throttles` middleware does a few checks, and if there are too many request, it throws an [`ThrottleRequestsException`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/Middleware/ThrottleRequests.php#L200).

Because in Laravel all uncaught exceptions go through the Exception Handler, all we have to do in order to add our own 'rule' for handling the `ThrottleRequestsException`, and to render an Inertia response instead. [Luckily, this is fairly easy](https://laravel.com/docs/8.x/errors#rendering-exceptions):

```php
use Illuminate\Http\Exceptions\ThrottleRequestsException;
use Inertia\Inertia;

/**
 * Register the exception handling callbacks for the application.
 *
 * @return void
 */
public function register()
{
    $this->renderable(function (ThrottleRequestsException $e, $request) {
        return Inertia::render('Errors/TooManyRequests');
    });
}
```

As you can see, I now 'render' a custom TooManyRequests view that Inertia can then use. 

With other exceptions/errors, what I would instead suggest is to redirect back to the previous page with 'error' data flashed, which you can then `Inertia::share` and display in your Inertia layout or pages. This way, the user stays on the same page, and just sees the error pop up (for example, [as a flash message](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Shared/FlashMessages.vue#L12-L15)) whenever your specific 'http error' happens.

Hope this helps!

**Comment by ajnsn** [comment]
@claudiodekker @reinink Thank you for your detailed explanations and code samples. Thank you also for the time and effort you put into Inertia. I really love working with it.

I do now better understand that it's impossible to receive the error codes like with a XHR request. 

Currently I have sligtly different approach than rendering an error component.
I catch the exceptions and then simply redirect the user back with a notifcation message.
Example for the `TokenMismatchException`

```php
if ($exception instanceof TokenMismatchException) {
    return redirect()->back()->with('notification', [
        'variant' => 'danger',
        'title' => 'Session expired.',
        'text' => 'Sorry, your session has expired. Please try again.',
    ]);
}
````
*Still using the Laravel < 8.0 approach here.

Inertia then shares this notification to Vue

```php
Inertia::share([
    ...
    'notification' => function () use ($request) {
        return $request->session()->get('notification');
    },
    ...
]);
```

Inertia-Vue passes the prop to Vuex.

```javascript
new Vue({
    el: '#app',
    store,
    render: h =>
        h(Inertia, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                resolveComponent: name => require(`./pages/${name}`).default,
                transformProps: props => {
                    if (props.notification) {
                        store.dispatch('notifications/add', props.notification);
                    }
                   ...
                },
            },
        }),
});
```

This works well and I very happy with it as it's universal, does not repeat and works with server rendered error messages. I am also using it for all sucess messages. Just sharing it here "fyi". Comments welcome.

Back to the original topic:
It's still feels strange to check for validation errors in the success callback. Also this code somehow repeats often, e.g. when redirecting, showing confirmation modals etc. - I have to do this over and over again. 

I do not have a solution for this right now. But one idea might be to allow `Inertia::render` somehow pass a flag to initiate a different callback?

**Comment by claudiodekker** [comment]
Yeah, so, normally, you don't actually have to check anything in the callback. 
Instead, you should see the page as a single view that represents _all possible states_. 

**An example**: Let's imagine you have a page, on which you have a button that dispatches a job to a queue or something, and if you click that button, you want your front-end to show a 'special message'.

So, what we'll do first, is render the page using `Inertia::render`, at which point we'll also pass in our our `specialMessage` prop. This might seem weird, because an _initial page load_ does not have a special message to display, but remember that an Inertia page represents all possible states:

```php
// ...

Inertia::render('Page/Example', [
    'specialMessage' => Session::get('specialMessage')
]);
```

Next, on our Inertia view, let's write some logic for it:

```html
<template>
  <div>
    <div v-if="specialMessage" class="text-green-400">{{ specialMessage }}</div>
    <inertia-link href="..." method="post">Dispatch Job Button</inertia-link>
    <!-- Some other code -->
  </div>
</template>

<script>
export default {
  props: [
    'specialMessage'
  ]
}
</script>
```

Next, on the POST endpoint, we'll write some back-end code that sets that `specialMessage` key to the session:
```php
// ...

return redirect()
    ->route('page.example')
    ->with('specialMessage', 'Congratulations! The job was dispatched!');
```

Now, when the user loads the page initially, the `specialMessage` will be `null`, and the message won't be displayed. However, when the user clicks the button, the `Inertia.post` request happens, followed by a redirect that returns our Inertia response.

Now, here's the magical part: Because the page that the user is on _before_ clicking on the button is the same as the page the user ends up on _after_ the post request has finished, **Inertia will only swap the props of the page that the user is already on**.

The result is that Vue will detect that (some of) the props have changed, which causes it to update the template, and display the message, all without writing any 'custom' toggling logic in Vue depending on the 'request'.

Finally, I'd like to add that this might seem _heavy_,  doing checks on the back-end all of the time, but this has also been thought about. For that, I'd recommend to check out [this section of the documentation](https://inertiajs.com/partial-reloads).

Hope this helps!

**Comment by ajnsn** [comment]
@claudiodekker Thank you !
