### ISSUE TITLE
[inertia-svelte] not working on ie11.

### ISSUE THREAD

**Issue by dvlpr91** [inertiajs/inertia#258]
Doesn't work on ie11. (added core-js)

I don't know in detail, but when I check the error log, it shows near "@inertiajs/inertia-svelte/src/link.js".

**Comment by dvlpr91** [comment]
> Doesn't work on ie11. (added core-js)
> 
> I don't know in detail, but when I check the error log, it shows near "@inertiajs/inertia-svelte/src/link.js".

```
...
mix.polyfill({
  useBuiltIns: 'entry',
  targets: {
    ie: 11
  },
  entryPoints: 'all',
});
...
```

**Comment by claudiodekker** [comment]
Hi,

Unfortunately, all of Inertia doesn't officially support IE11, for a couple of reasons:
- [Less than 1,5% of the internet still uses IE11](https://caniuse.com/usage-table)
- [Microsoft already dropped support for it themselves](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666), as well as [others (such as GitHub, Twitter, YouTube, Facebook etc.)](https://death-to-ie11.com/)
- Because we're still actively developing new features for Inertia, dropping IE11 support allows us to spend less time and effort on building and maintaining 'workarounds' that only IE11 requires.
- By the time Inertia reaches what is considered to be 'stable' by many (1.0.0), it can pretty much be guaranteed that even more websites will drop IE11 support, which results in less and less people using it on a daily basis.

That said, If you can provide more information regarding your specific error, I'd be happy to look into it to see if we can find a workaround, but my recommendation is to either drop IE11 support as well, or to simply not use Inertia, because even if you get things working, it's quite unlikely that other things won't start breaking going into the future.

**Comment by dvlpr91** [comment]
@claudiodekker 


Thank you very much!

I have a question. Is it correct that `inertia js` cannot be used even with babel's transpile and polyfill? 
(using any tool such as core-js)

I tried using `laravel-mix-poliyfill` but it failed...

I need help.
