### ISSUE TITLE
CORS/Proxy issue when using remote-development

### ISSUE THREAD

**Issue by sunscreem** [inertiajs/inertia#265]
I'm using VS Code and use remote-development. Works great.

It proxies my remote server say `http://mydomain.com` to `http://localhost:61234`.

I've installed JetStream + Inertia.js all working great ... except when I submit a post request. 

Recreating the issue:

Say my page/form is at `http://localhost:61234/mypage`.

I submit the post request. 

That works just fine (ie. it hits the laravel controller no problems)

The 303 is generated but its `location` is set in the headers:

```
location: http://mydomain.com/mypage
```
It then throws a CORS error:

![image](https://user-images.githubusercontent.com/7523595/96375917-e40e8480-1173-11eb-98de-300a5c3b0760.png)

What I need in that redirect is:

```
location: http://localhost:61234/mypage
```

FYI In my controller I'm using:

```
 return Redirect::route('mypage')->with('success', 'operation successful.');
```

FWIW `dd(route('mypage'))` returns: `/mypage`

So - I'm thinking this might be my lack of understanding of Laravel's Redirect vs any issue with inertia.js but I'm struggling to work out if the problem is with Laravel, Jetstream or Inertia itself.

Apologies in advance if this is not an inertia bug - not sure where else to ask for help.

**Comment by claudiodekker** [comment]
Hi,

When a redirect is made, Laravel does a bunch of things to figure out the URL that it should redirect you to. If you dig down the rabbit hole long enough, you'll eventually notice that it [uses the current request to figure out the origin that the request came from](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Request.php#L94).

In your situation, your request gets sent to a localhost domain, but because of the proxy, Laravel _actually_ receives it from http://mydomain.com. Because of what I just described, Laravel then redirects the user to mydomain.com.

Now, normally, this wouldn't cause much trouble, but because Inertia uses an XHR/AJAX request under the hood, a [CORS policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) applies to it's behavior, which blocks requests that aren't to the same domain.

The way to solve this, is to allow the origin instead of to block it. For this, I recommend you to check out [the documentation here](https://github.com/fruitcake/laravel-cors), which is the middleware that Laravel uses for this.

Hope this helps.

**Comment by sunscreem** [comment]
Thanks @claudiodekker - appreciate your patience on this.

I thought about it and while your solution would have got rid of the CORS problem, it would have still forced the browser to redirect to the non-proxied url.

After much experimenting I found a fairly simple solution. In my routes file I have this:

```
if (env('FORCE_ROOT_URL')) {
    URL::forceRootUrl(env('FORCE_ROOT_URL'));
}
```
Where the FORCE_ROOT_URL is set to `http://localhost:61234/` 

All works a treat again now. 

My word this stuff can mess with your head!
