### ISSUE TITLE
How could we load data as JSON object instead of a inertia::render view.

### ISSUE THREAD

**Issue by santlalgodara** [inertiajs/inertia#269]
I need to load products on category drop-down change. everything in Laravel is working but inertia gives me a problem. Inertia loading view instead of product JSON return. 

```
this.$inertia.post(route('product.filter'), categoryId).response (( data){
cosole.log(data);
})
```

**Comment by reinink** [comment]
So, depending on how you're building your app, you have two choices:

## 1. Use xhr/fetch

Sometimes it makes more sense to simply use xhr/fetch directly, instead of using an Inertia request. Inertia links/visits are intended for visiting pages, and therefore all Inertia requests must receive an Inertia response. Returning plain JSON will cause the non-Inertia response modal to be shown.

```js
axios.post(route('product.filter'), { category: categoryId }).then(response => {
  this.products = response.data.products
})
```

## 2. Use Inertia

However, generally when it comes to filtering data, I'll still use Inertia visits for this. Simply make a visit back to the same page (the products index page I'm assuming in this situation), and pass through the `categoryId` from the category dropdown.

```js
Inertia.get(route('products'), { category: this.categoryId })

// Or even just:
Inertia.reload({ data: { category: this.categoryId }})
```

Assuming that your Vue page component is displaying the `products` prop, this will cause the products to automatically update, since props are reactive.

I hope that helps!
