### ISSUE TITLE
Custom axios paramsSerializer not working

### ISSUE THREAD

**Issue by lorlab** [inertiajs/inertia#282]
Hi! I am trying to set a custom axios paramsSerializer (to use [spatie/laravel-query-builder](https://github.com/spatie/laravel-query-builder)) but I am struggling to get it working. It used to work on an old project using older versions of inertia and axios, in fact I got the code from this issue: #52 which was trying to achieve the same thing.

In my app.js I set the function:

```
import axios from 'axios'
import qs from 'qs'

axios.interceptors.request.use(
  function (config) {
    console.log(config)
    config.paramsSerializer = function (params) {
      return qs.stringify(params, { arrayFormat: 'comma', encode: false })
    }
    return config;
  },
  function (error) {
    return Promise.reject(error)
  }
);
```

And in my component: 

`this.$inertia.replace(this.$route('contacts.index'), { data: { search: 'foo' } })`

What's happening is that the console.log shows this config: 

`{ url: "https://mysite.test/contacts?search=foo", method: "get", params: {} }`

 For some reason the params are already part of the url. 

In my old project this was the result: 

`{ url: "https://mysite.test/contacts", method: "get", params: { search: 'foo' } }`

Any ideas? Thanks!

**Comment by reinink** [comment]
So we recently updated Inertia.js to merge query strings with the data (see #264), which is why you're getting this behaviour.

It appears that all you're looking to change is the query string format, correct? As a workaround, I think you can still use an  axios interceptor, but instead of looking at the `params`, simply parse the `config.url`, and then re-encode it using the query string format you prefer (using the `qs`) library.

Totally untested, but something like this:

```js
import axios from 'axios'
import qs from 'qs'

axios.interceptors.request.use(
  function (config) {
    let url = new URL(config.url)
    url.search = qs.stringify(qs.parse(url.search), { arrayFormat: 'comma', encode: false })
    config.url = url.location
    return config
  },
  function (error) {
    return Promise.reject(error)
  }
);
```

I do wonder two things here:

1. Should Inertia.js provide an option to encode query strings using the commas format?
2. Why doesn't the spatie/laravel-query-builder package support the more classic query string array format (`a[]=b&a[]=c)?

**Comment by lorlab** [comment]
Hey thanks! Your workaround seems to be working fine! 
I'll paste what worked for me for anyone who might come across a similar problem:

```
axios.interceptors.request.use(
  function (config) {
    let url = new URL(config.url)
    url.search = qs.stringify(qs.parse(url.search, { ignoreQueryPrefix: true }), { arrayFormat: 'comma', encode: false })
    config.url = url.href
    return config;
  },
  function (error) {
    return Promise.reject(error)
  }
);

```
To answer your questions: 
1. It would be handy as I think a lot of people are using that spatie library and will come across this problem. Even better would be to pass a custom "paramsSerializer" function like axios allows.
2. I think it is because it follow the [JSON API specification](https://jsonapi.org/) which uses commas

**Comment by mpbarlow** [comment]
Just to throw my two cents in here as well: rather than intercepting the request in order to rewrite the query string, you could also just do something like:
```js
this.$inertia.visit(`${route}?${myCustomQueryString}`, {
  preserveState: true,
  ...otherOptions
})
```
Both require you to compute the query string yourself (either with `qs` or some other means), but with the interceptor approach I would be a little concerned about it sticking around and messing with subsequent requests, whereas this is totally self contained.
