### ISSUE TITLE
Request Breaking

### ISSUE THREAD

**Issue by anubra266** [inertiajs/inertia#300]
I'm not really sure, but I think this error only occurs on slow Connections.
```
Uncaught (in promise) TypeError: e.response is undefined
```
I use React with Inertiajs.

**context:** I send a request, it's slow, I suppose, but then it never finishes loading. I open my console and find that error. A javascript break like that means, even when the response is back, (I know that because my changes are applied on a page reload), the props can't be updated until a full page reload.

I searched wide for the cause of this error, I knew it was definitely not me, because it could happen on any of my requests, and the console pointed to some code, that was definitely not written by me.

The best explanation i found said it was from **Axios promises** That person used react too. He said the error occured before my response could get back. The only instances of Axios in my app right now is Inertia. Just wanted to know, if this means anything to you.

Thanks.

**Comment by claudiodekker** [comment]
Hi,

I'd love to look into this, but unless we have something that's a bit more traceable/debuggable there isn't much we can do. Could you copy the whole stack trace instead of just the error message? 

Here's how you can do that:
1. 'Expand' the console error
2. Right-click the error, and save it to a file
3. Attach the log file to a comment to this issue by dragging it into the comment message box

![Screenshot 2020-10-28 at 18 07 23](https://user-images.githubusercontent.com/1752195/97471121-ad412700-1948-11eb-9a0e-0e0b251a71ce.png)

Thanks!

**Comment by reinink** [comment]
Hey @anubra266, please feel free to update this issue with a full stack trace, but until then I am going to close this.
