### ISSUE TITLE
Inertia Link preserveState

### ISSUE THREAD

**Issue by anubra266** [inertiajs/inertia#301]
@claudiodekker 

My Menu is like 
```
 					<Menu.Item key={`menu-${NavItem.route}`}>
                        <InertiaLink
                            preserveScroll
                            preserveState
                            href={route(NavItem.route)}
                        >
                            {NavItem.name}
                        </InertiaLink>
                    </Menu.Item>
```

And i have normal state
```
const [editorState, setEditorState] = useState(
        BraftEditor.createEditorState("Editor Content")
 );
```

But The state is set to default once i visit the renavigate to the page. Where Am i getting it wrong please?

**Comment by reinink** [comment]
I'm not really following the issue here, but the `preserveState` feature only works when making page visits to the **same page component**. Is that what you're doing?

**Comment by anubra266** [comment]
@reinink Oh, I doubt that's what I'm doing.

I have the state on my edit page.
I navigate to Home page, then I renavigate to edit page.
Should edit's state be preserved?

**Comment by reinink** [comment]
No, not when going from one page component to another.

The way `preserveState` works is by preserving the state of an existing page component when navigating to the same page. By default Inertia will set a new key on the page component, forcing a full re-render. By setting `preserveState` to `true`, this tells Inertia to not do that.

However, when you're making visits to a totally different component, there is no state to preserve, because you're getting a whole new component rendered.

It sounds like in your situation you want something like local storage to save your editor state...or you could even save this in the server's session, and repopulate this when going back to the editor.

Either way...this is not what `preserveState` is intended for. 👍

**Comment by anubra266** [comment]
Ok I understand. Thanks a lot.

**Comment by reinink** [comment]
@anubra266 Happy to help! 🤟
