### ISSUE TITLE
No access to Custom Inertia Props

### ISSUE THREAD

**Issue by anubra266** [inertiajs/inertia#311]
As at version 0.5.0, We could send custom props with an Inertia Visit. Catch them elsewhere and act on them.
![image](https://user-images.githubusercontent.com/30869823/97788773-b8e85400-1bbb-11eb-9d77-87dd9551ee7c.png)

There I have `progressIndicator:false`

As at version 0.6.1
This is not available.
![image](https://user-images.githubusercontent.com/30869823/97788801-e6350200-1bbb-11eb-8f1b-9d7423de68db.png)

Please change that.

**Comment by claudiodekker** [comment]
Hi,

Unfortunately, this "feature" was not documented or intentionally developed to work like this, and as such it no longer working as of a newer version is not considered to be a bug. I understand that this might be frustrating.

What you could do instead, is to set your props to a reserved state object directly before making a call, and retrieve and act on that state elsewhere.

**Comment by claudiodekker** [comment]
@anubra266 Am I correct in assuming that all you're trying to do is conditionally disable the progress bar, or do you also use these 'custom props' for other objectives?

**Comment by anubra266** [comment]
@claudiodekker Sorry for the late answer. Today was a jammed up one for me.
Sincerely speaking, I don't have much use for the feature yet, but I understand that It's always better when we have more freedom in customizing the stacks we work with.

But it will definitely be worthwile in future projects.
In fact I only found this out because I was working with someone who used a lower version in his code, and didn't realise that it was deprecated.
I tried to implement the same it refused to work. He updated and his app was breaking.

In this note I would also like to suggest that in future releases, it would be best to inform us of deprecated practices, so we don't go crying over our code after an update. 
Thanks a lot.

**Comment by claudiodekker** [comment]
> Sincerely speaking, I don't have much use for the feature yet, but I understand that It's always better when we have more freedom in customizing the stacks we work with.

So, right now you're _only_ using it to disable a progress indicator, correct? 

We actually don't want to allow too much flexibility if there's no realistic use-case, because it'll make maintaining the project harder and cause more frequent breaking changes.

> But it will definitely be worthwile in future projects.
> In fact I only found this out because I was working with someone who used a lower version in his code, and didn't realise that it was deprecated.
> I tried to implement the same it refused to work. He updated and his app was breaking.
>
> In this note I would also like to suggest that in future releases, it would be best to inform us of deprecated practices, so we don't go crying over our code after an update.

I see, alright. Just to clarify, this was never a real feature. The fact that it used to work on an older version but stopped working on a newer versions is purely accidental. That's why we don't consider this a bug.

If you want to know of what are considered deprecated practices, it's actually fairly easy:
- If it works, but it's deprecated, you will see a [console warning](https://i.stack.imgur.com/mbW6P.png) in your browser that will tell you about this.
- If it works, but it's **not mentioned** in the documentation on [inertiajs.com](https://inertiajs.com), **do not use it, as it might break without warning**.
- If it doesn't work, but it is mentioned in the documentation on [inertiajs.com](https://inertiajs.com), then that's a bug.

Hope this helps!

**Comment by anubra266** [comment]
Yeah that helps.

But this means there will be no use case for the custom progress bar development in the Docs.
The inertia progress bar would already cover every use case.

**Comment by reinink** [comment]
> The inertia progress bar would already cover every use case.

Not if you want a different progress bar style.

> In this note I would also like to suggest that in future releases, it would be best to inform us of deprecated practices, so we don't go crying over our code after an update.

Point here is, we had no idea that making this change would inadvertently have this side-affect for non-documented way of using the library. If we did, we'd probably have mentioned it.
