### ISSUE TITLE
href-prop cannot be null

### ISSUE THREAD

**Issue by NicTorgersen** [inertiajs/inertia#326]
I use inertia-vue and implemented a paginator component wrapping Laravel's [paginate()](https://laravel.com/docs/8.x/pagination#introduction) (toArray).  
The `links` object of the response returns null when there are no `previous` or `next` pages:

```javascript
// on the last page
{
    links: {
        first: 'https://url.com?page=1',
        last: 'https://url.com?page=4',
        next: null,
        prev: 'https://url.com?page=3',
    },
}

// on the first page
{
    links: {
        first: 'https://url.com?page=1',
        last: 'https://url.com?page=4',
        next: 'https://url.com?page=2,
        prev: null,
    },
}
```

I noticed there is a `required`-validator in the inertia-link component for the `href`-prop, and I was able omit this behaviour by sending a random string (in my case `'#'` and set `pointer-events: none;`.

Very tiny annoyance. I forked to try and apply a fix, but don't have the testing resources required to do so confidently.

To sum it all up: **If the `href`-prop is null, I would expect the element to be rendered, but not have any click event handlers, or similar, applied.**

Alternatively add a `disabled`-prop which would terminate early.

**Comment by sebastiandedeyne** [comment]
I agree that the `href` prop shouldn't be required.

> If the href-prop is null, I would expect the element to be rendered, but not have any click event handlers, or similar, applied.

However, I don't agree with this. If `href` is empty, it should link to the current page to mirror the `a` tag behaviour.

**Comment by NickSdot** [comment]
> However, I don't agree with this. If `href` is empty, it should link to the current page to mirror the `a` tag behaviour.

I also did run in this issue and I would like to second what @NicTorgersen proposed. Please let me try to make a point @sebastiandedeyne.

Let's assume we are talking about normal HTML, then the behavior is as following...

**This will link to the same page:**
`<a href="">Test Empty</a>` -> https://domain.tld/current-page

**This will not link at all:**
`<a>Test No href</a>`

So, in fact both ways would 'mirror the `a` tag behaviour'.

Now, let's take the Laravel pagination as an example. In middle of the page items there is the '...' placeholder (see after page 10) to keep the list short:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/32384907/125455406-44190441-9068-46f4-afb0-41e1a7998481.png">

It has the following data provided by Inertia/Laravel:. As you can see `url` is, correctly, set to `null`, which in Vue – same as in plain HTML – would render the link, but not use the href-attribute at all.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/32384907/125455300-726718e6-e4da-4433-952a-6ed2736a5b36.png">

If the `href` attribute would **not be rendered at all**, this element would (imho correctly) not link anywhere and would **not** have a mouse cursor pointer.

If the `href` attribute would **be rendered empty**, this element would (imho wrongly) link to the current page and would have a mouse cursor pointer.

The same behavior by the way also applies for the next/previous links of the pagination. To have a good user experience the buttons should not be clickable if there is `null` given.

So let's assume you guys go with the way mentioned by @sebastiandedeyne. Then the only option to work around this would be to work with `v-if'/`v-else` which will lead to a lot of code duplication and verboseness. 

**Instead of:**
```html
            <inertia-link v-bind:href="pagination.prev_page_url"
                          v-bind:class="{ 'hover:bg-gray-50': isNotFirstPage() }"
                          v-bind:as="pagination.prev_page_url ? 'a' : 'span'"
                          class="bg-white relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white">
                Previous <span class="sr-only">Previous <span v-if="label">{{ label }}</span><span v-else>results</span></span> <ChevronLeftIcon class="h-5 w-5 ml-4" aria-hidden="true" />
            </inertia-link>
            <inertia-link v-bind:href="pagination.next_page_url"
                          v-bind:class="{ 'hover:bg-gray-50': isNotLastPage() }"
                          v-bind:as="pagination.next_page_url ? 'a' : 'span'"
                          class="bg-white relative ml-3 inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white">
                Next <span class="sr-only">Next <span v-if="label">{{ label }}</span><span v-else>results</span></span> <ChevronRightIcon class="h-5 w-5 ml-4" aria-hidden="true" />
            </inertia-link>
```
**I must go with** (several times in the file):
```html
            <inertia-link v-if="pagination.prev_page_url"
                          v-bind:href="pagination.prev_page_url"
                          v-bind:class="{ 'hover:bg-gray-50': isNotFirstPage() }"
                          v-bind:as="pagination.prev_page_url ? 'a' : 'span'"
                          class="bg-white relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white">
                Previous <span class="sr-only">Previous <span v-if="label">{{ label }}</span><span v-else>results</span></span> <ChevronLeftIcon class="h-5 w-5 ml-4" aria-hidden="true" />
            </inertia-link>

            <div v-else
                 class="bg-white relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white">
                Previous <span class="sr-only">Previous <span v-if="label">{{ label }}</span><span v-else>results</span></span> <ChevronLeftIcon class="h-5 w-5 ml-4" aria-hidden="true" />
            </div>

            <inertia-link v-if="pagination.prev_page_url"
                          v-bind:href="pagination.next_page_url"
                          v-bind:class="{ 'hover:bg-gray-50': isNotLastPage() }"
                          v-bind:as="pagination.next_page_url ? 'a' : 'span'"
                          class="bg-white relative ml-3 inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white">
                Next <span class="sr-only">Next <span v-if="label">{{ label }}</span><span v-else>results</span></span> <ChevronRightIcon class="h-5 w-5 ml-4" aria-hidden="true" />
            </inertia-link>

            <div v-else
                 v-bind:as="pagination.next_page_url ? 'a' : 'span'"
                 class="bg-white relative ml-3 inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white">
                Next <span class="sr-only">Next <span v-if="label">{{ label }}</span><span v-else>results</span></span> <ChevronRightIcon class="h-5 w-5 ml-4" aria-hidden="true" />
            </div>
```

Since there is 5 link-elements in the HTML (prev/next, links, prev mobile, next mobile), in my case I end up with 141 lines in the files instead of the 94 lines it could be if the `href` would not be rendered if `null` is given. That's 47 lines more, without any visible benefit.

Therefore, in my opionion, the behaviour without rendering the `href` is the better way to go. I don't know what's the reasons why you would prefer to render the `href` without content, but if there is any, then it maybe is a good idea to add a whole new attribute to be able explicitly disable the `href` if wanted.

**Comment by NickSdot** [comment]
If I did not miss something, this got fixed with https://github.com/inertiajs/inertia/pull/843 (thanks! ) and can get closed.

cc @NicTorgersen / @reinink

**Comment by reinink** [comment]
Yup, thanks for the heads up!

**Comment by truesteps** [comment]
I'm experiencing the same issue with v1 of inertia, has this been part of the release?
