### ISSUE TITLE
Leitura de objeto JSON

### ISSUE THREAD

**Issue by brenoriot** [inertiajs/inertia#333]
Boa noite, gostaria de saber como eu faço para realizar um post em uma rota LARAVEL, onde esta rota irá me retorna uma resposta JSON. Gostaria de saber como posso fazer para ler este json com InertiaJS, já procurei no google e não encontrei, perguntei em comunidades e ninguém respondeu.

Como posso realizar uma consulta em uma rota que irá responder um objeto json, e no front ler este objeto?

**Comment by claudiodekker** [comment]
Hi @brenoriot,

I'm using Google Translate in an attempt to understand your question, so please let me know if I'm misunderstanding it: You're trying to do a Laravel `POST` call, which returns JSON, and you would like to use this JSON data within Inertia.

So, depending on how you're building your app, there's two choices:

## 1. Use Inertia

Generally when it comes to updating the current view with data that's changed (e.g. a filter or search box), our recommendation is to simply use Inertia visits for this. 

To do so, first make an Inertia visit to an endpoint that you can use to process your data and filter/search or whatever it is you're trying to achieve:
```js
Inertia.post(`/users`, { name: query })
```

Then, instead of returning JSON, you return an `Inertia::render` response that renders the same page that you were already on. This allows Inertia to be smart about it, and to only update the current view with the data that's changed.

## 2. Use xhr/fetch

Sometimes it makes more sense to simply use xhr/fetch directly, instead of using an Inertia request. 

Inertia links/visits are exclusively intended for visiting pages, and therefore all Inertia requests must receive an Inertia response. Returning plain JSON will cause the non-Inertia response modal to be shown.

```js
axios.post('/users', { name: query }).then(response => {
    this.users = response.data.users;
})
```

I hope this helps!
