### ISSUE TITLE
Replace ./ with @

### ISSUE THREAD

**Issue by devlloedy** [inertiajs/inertia#373]
Hi i would like to know how can i replace ./ with @. I am following pingcrm example but when i do it with my fresh app
it always throws an error of unknown module. 

documentation -> resolveComponent: name => require(`./Pages/${name}`).default,
what i want -> resolveComponent: name => require(`@Pages/${name}`).default,

**Comment by maggz69** [comment]
@devlloedy 
**_Laravel with Inertia_**
In order to make use of @ rather than relative directory importing , you need to create a webpack alias. You can find more information here. [Webpack config alias documentation](https://webpack.js.org/configuration/resolve/).

**Comment by claudiodekker** [comment]
Hi @devlloedy,

In addition to what @maggz69 said, you basically need to [add this alias](https://github.com/inertiajs/pingcrm/blob/master/webpack.mix.js#L40) to your `webpack.mix.js` if you're using Laravel Mix.

In addition, certain editors (like PHPStorm) don't understand the `webpack.mix.js`, and as a result refuse to create imports using the `@` alias automatically. To fix this, you can create a separate `webpack.config.js` file in your project root, and add the whole webpack configuration there:

```js
const path = require('path')

module.exports = {
    output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
    resolve: {
        alias: {
            'vue$': 'vue/dist/vue.runtime.esm.js',
            '@': path.resolve('./resources/js'),
        },
    },
}
```

Then, inside your `webpack.mix.js`, simply import it instead of passing in the `webpackConfig` object manually:
```js
const mix = require('laravel-mix');
const webpackConfig = require('./webpack.config');

// ...

mix.webpackConfig(webpackConfig);
```

(Credit for this solution goes to https://stefanbauer.me/tips-and-tricks/autocompletion-for-webpack-path-aliases-in-phpstorm-when-using-laravel-mix)

Hope this helps!
