### ISSUE TITLE
inertia and vuex

### ISSUE THREAD

**Issue by makroxyz** [inertiajs/inertia#420]
Hi I'm trying to use inertia in a large project and I'd like to remove vuex from it.

Could I use $page.props with some attributes which I will not declare as page component props, then mutates it directly in components (like this.$page.props.vuex_state_attribute = 'test')? Is this the right way?

Thanks

**Comment by claudiodekker** [comment]
Hi,

While this really belongs in the (relatively new) [help section of the Discussions tab](https://github.com/inertiajs/inertia/discussions/categories/help-vue), I'll still do my best to answer this here this time, but it would be appreciated if you could post your questions over there for questions next time. 

I'll also be closing this issue for this exact reason, but that doesn't mean that you should consider this specific conversation here locked. Feel free to comment in case you have any related follow up questions etc.

**Comment by claudiodekker** [comment]
Hmm.. Modifying props directly isn't really the way Inertia is intended to be used, because this means you're essentially placing the 'client' and 'server' in two [different states](https://inertiajs.com/who-is-it-for#:~:text=It%20means%20client-side%20state%20management).

That said, there are valid use cases (such as temporary things such as opening or closing a section) that really don't have any reason to be tracked on the back-end, and in those situations what I would recommend you to do is [use Vue's native props and $emit functionality to share information upwards and downwards within components](https://vuejs.org/v2/guide/components.html#Emitting-a-Value-With-an-Event).

Since the things that you pass as props from your back-end usually have a 'significant meaning' or are heavy in state (otherwise you probably would've hard-coded them in your Vue components/pages), the Inertia way to solve this problem is to make a new Inertia request to the back-end. The back-end can then process this modified state if needed, and send a new response with the 'updated' prop. When done correctly, the user won't really notice this.

So, when making a new request, there's a couple of things you might be asking yourself:
- **But what about things that the user is doing (e.g. scrolling, interacting with the page)? Won't that all get reset??**
Yes, as of default, it will. However, an option exists that you can pass through your request, that makes sure that only the page's props get updated: https://inertiajs.com/links#preserve-state / https://inertiajs.com/manual-visits#component-state

- **Okay, but what about my other props? Won't they also get re-fetched from the database? Isn't this really heavy for such a simple thing?**
For sure! And for this reason, another option exists that allows you to 'only' get a fresh version of the given props / make a partial reload: https://inertiajs.com/partial-reloads#making-partial-visits

Hope this helps!
