### ISSUE TITLE
Add option to disable Inertia Modal

### ISSUE THREAD

**Issue by philippkuehn** [inertiajs/inertia#43]
Hey, I try to implement Inertia into a very large application. In the beginning I can only replace some parts of the app, so I run into the problem that I can't use `<inertia-link />` there. It's because whenever I link into a legacy part of the app, the link will be opened in a modal. Since this is cool for something like error pages, it would be great to have an option to change that behavior. What do you think?

**Comment by reinink** [comment]
So, early on in my Inertia development I tried to make it that when a non-Inertia response comes back from the XHR request, it would automatically display that as the current page, instead of in a modal. However, this was not possible to get working properly, especially when it came to history management, despite both @adamwathan and my best efforts. We seriously spent a _ton_ of time on this...and our determination was that it couldn't be done.

That said, Inertia can totally work in an app that has some Inertia pages, and some server-side rendered pages. If you have pages in your app that are not Inertia pages, simply make those visits using normal links, and not using `<inertia-link>`. If you are making an Inertia request, you must return an Inertia response.

**Comment by philippkuehn** [comment]
Thanks for your explanation!

**Comment by diverispetros** [comment]
I am struggling with something similar. I've got a mixed app. which renders a single inertia driven page from a dedicated controller. In my controller upon update of resource I do 

```
public function update() 
{
        ...
        return \Redirect::route('alphabet')->with('success', 'Terms updated.');
}
```
No matter why I do, the alphabet (non inertia/vue route) page comes up in a modal.

Looking at your code I've tried to set x-inertia to true

```
public function update() 
{
        ...
        $headers[] = ['x-inertia'=>true];
        return \Redirect::route('alphabet')->with('success', 'Terms updated.');
}
```
but this doesn't seem to have an effect either.

**Comment by jakedowns** [comment]
@reinink is there any good way to suppress the modal other than using like... css? we still have the occasional error that we'd rather suppress and display our own toast notification when something went wrong, rather than having the page popup in an overlay. it doesn't bother me, as a dev, but our designers and product managers are not too keen on how it currently operates.

is there an error handler we could jack into for doing our own error handling when inertia decides that it _needs_ to display a modal?

Re: mixing inertia and legacy routing, we implemented a "smart-link" component that helped us be consistent in our templates (not having to manually wrangle <a> vs <inertia-links>, while letting us phase things in on a route-by-route basis:
https://github.com/jakedowns/inertia-smart-link/blob/main/SmartLink.vue

**Comment by alexryall** [comment]
@jakedowns You can stick something along these lines in your app.js file, the preventDefault() will stop the modal opening and you can add whatever code you want before that.

```
Inertia.on('invalid', (event) => {
    alert('custom error handling')
    event.preventDefault()
})
```

**Comment by jakedowns** [comment]
@alexryall thanks!

**Comment by gustavoconter** [comment]
> @enriquemdev 
> Is this still valid solution for Laravel 11 with Inertia react? I cant find where to put this snippet.

Yes, it should still be a valid solution, however the syntax changed after Inertia `v1.0`. You could put this updated code on your `app.js` or `app.ts`. I think the best place to put it is right before the `createInertiaApp` function call. This makes sure that the listener is registered globally.

```typescript
import { router } from "@inertiajs/react";

router.on('invalid', (event) => {
  event.preventDefault();
});
```

**Comment by savhascelik** [comment]
thank @alexryall 
sometimes when blade templates and inertia are used together, blade urls also open in the same modal, it can be annoying, a solution like below will provide a smooth transition.

```
router.on('invalid', (event) => {
    event.preventDefault()
    
    const response = event.detail.response
    window.location.href = response.request.responseURL
})
```
