### ISSUE TITLE
Method delete is not supported

### ISSUE THREAD

**Issue by AndrGutierrez** [inertiajs/inertia#497]
### Versions:

- `@inertiajs/inertia` version: 6.14.11
- `@inertiajs/inertia-react` version: 6.14.11

### Describe the problem:

When I use Inertia.delete on react, data is deleted as expected, but shows an error that says DELETE method is not supported. supported methods: GET, HEAD, POST

I have to reload the page to see the changes (I guess it is because of the redirect to a route that uses get method

### Steps to reproduce:

create `Route::resource` routes like this

`Auth::routes(); 
Route::resource('users', 'App\Http\Controllers\Backend\PostController')->middleware('auth');`

create destroy method

`use App\Models\Post; 
class UserController extends Controller
{
    public function destroy(User $user){
        $user->delete();
        $return back();
    }
}`

in any React component in a route that uses get, head or post method do this:
`Inertia.delete('/users/', user.id)`

**Comment by ajnsn** [comment]
@AndrGutierrez The signature of the the `delete` method is 

```js
this.$inertia.delete(url, options)
```

Can you please try the following change:

```diff
- Inertia.delete('/users/', user.id)
+ Inertia.delete(`/users/${user.id}`)
```

**Comment by claudiodekker** [comment]
Thanks for helping out here @ajnsn. 👍

**Comment by AndrGutierrez** [comment]
still not working :[

**Comment by claudiodekker** [comment]
Hi @AndrGutierrez,

Where are you receiving this error from? Could you perhaps provide a screenshot? Because there's never been any programming anywhere in Inertia that either shows or logs a message to the console that a method "is not supported".

Instead, what I'm assuming is happening, is that you're using the `DELETE` method to an endpoint/URL that, as the message is already informing you of, does not support the `DELETE` method. Here's why I believe this to be the case: When using Laravel on a development environment, instead of just crashing with an HTTP error, [Ignition](https://github.com/facade/ignition) will be used to render the error to the browser. Because this in turn means that a non-inertia response is returned from the Inertia request, Inertia will conveniently [render this error-response in a modal](https://inertiajs.com/error-handling#development). 

A good example of such an error can be seen on the PingCRM demo site:
![Screenshot 2021-02-19 at 16 20 07](https://user-images.githubusercontent.com/1752195/108523547-559b4280-72ce-11eb-8850-a111ac514fd5.png)

**Comment by Arturexe** [comment]
It you're working with urls and not with `ziggy`, you have to embed the `$id` parameter in the `url string`. In my case, I had to concatenate `props strings` together:

`Inertia.delete(props.options.url + props.data['id'])`

**Comment by oal2727** [comment]
the solution with respect to deleting was with the following
 
![image](https://user-images.githubusercontent.com/41652885/175186270-b146e4b5-eadf-4733-8584-dbf3777f3f30.png)

**Comment by sarjid** [comment]
### You Can Delete Easily Following This Code

![destroy](https://github.com/inertiajs/inertia/assets/53226726/6d7b3ab3-8b77-41dc-9098-38e9421e8c26)
