### ISSUE TITLE
Vue 3 - Manual visits in click handler throws deprecation warning

### ISSUE THREAD

**Issue by RobertBoes** [inertiajs/inertia#508]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

When using manual visits inside a DOM event handler a warning is thrown stating that visit promises have been deprecated.

> Inertia.js visit promises have been deprecated and will be removed in a future release. Please use the new visit event callbacks instead.

This obviously does not happen when using a separate method to call the visit.

I don't know if this might this cause issues when the visit promises are completely removed, or if the warning can safely be ignored

### Steps to reproduce:

A button with the following event handler causes the warning
```js
<template>
  <button @click="this.$inertia.get('/')">Test</button>
</template>
```

When using a method no warning is thrown, which is expected
```js
<template>
  <button @click="navigate()">Test</button>
</template>

<script>
import { Inertia } from '@inertiajs/inertia'

export default {
  methods: {
    navigate() {
      Inertia.get('/')
    }
  }
}
</script>

**Comment by reinink** [comment]
This has something to do with Vue, where it automatically calls "then" on the returned Inertia promise, which has been deprecated. Eventually we'll remove the promise and deprecation warning entirely, and this will go away. Since this is being caused by Vue, there really isn't much we can do about it right now.

I suspect this will happened when we release version 1.0. 👍
