### ISSUE TITLE
Yarn blows up something?

### ISSUE THREAD

**Issue by JoeCianflone** [inertiajs/inertia#53]
Hey, I'm leaving this partially as a marker for other people but if you run yarn instead of npm you could have some issues. Specifically yarn builds do something...different...so a page component seems not to get loaded. I'd get a `cannot find ./undefined` as an error in my console. I'd clear caches, recompile everything, make sure paths are correct and still nothing. I deleted my `node_modules` folder and still didn't get it to work. Then I deleted my `node_modules` and tried `npm install` and `npm run dev` and with no other change my pages were found. Normally I'd try to dig into this more to figure out what's going on I just don't have the time right now but maybe I'm doing something wrong with yarn or maybe this is a known issue. Happy to provide any other info if needed.

**Comment by rodrigopedra** [comment]
I had the same issue when adding a new package through `yarn add`. Lost several hours trying to figure out but couldn’t identify. Not complaining, just sharing, the package is great and I realize  it didn’t reach 1.0 yet. Also moved to npm and the problem was gone.

If there is anything I can help to find out what is the issue, please let me know .

**Comment by sebastiandedeyne** [comment]
I've had similar issues, and in my experience they've been related to yarn not properly resolving packages with git urls as their version.

I think these will be solved when we tag a 0.1 release in the near future.

In the meantime, if you're a yarn user, running `yarn upgrade` instead of `yarn` generally fixes the issue.

**Comment by reinink** [comment]
It's almost like we need a 0.1 release. 😂

**Comment by sebastiandedeyne** [comment]
v0.1.0 is released, so you can now depend on a proper version!
