### ISSUE TITLE
net::ERR_INTERNET_DISCONNECTED not caught by the new visit event callback onError

### ISSUE THREAD

**Issue by Archheretic** [inertiajs/inertia#530]
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-react` version: 0.5.4

### Describe the problem:
Disclaimer:
This bug has only been tested in Chrome Version 88.0.4324.192 (Official Build) (x86_64)

The bug:
When the client has no internet connection the new visit event callback onError is not triggered on http requests through Inertia. To catch this error we have to use the deprecated visit promises.

How it should behave:
When the client has no internet connection the event callback onError should catch the thrown error.

### Steps to reproduce:

In Chrome set internet connection to offline in Network tab.
![Screen Shot 2021-03-03 at 10 38 53](https://user-images.githubusercontent.com/10748292/109785729-b69b1280-7c0c-11eb-9a53-208233aa1b86.png)

After internet connection is set to offline execute the code below:
```js
import { Inertia } from '@inertiajs/inertia';

Inertia.patch(
	'/profile',
	{ someData: 'data' },
	{
		onError: errors => console.log('Caught by onError'),
	}
).catch(error => console.log('Caught by old promise'));
```

In your console "Caught by old promise" should now be logged out.
![Screen Shot 2021-03-03 at 10 57 44](https://user-images.githubusercontent.com/10748292/109788165-4b9f0b00-7c0f-11eb-8800-3f5c62ebe875.png)

**Comment by claudiodekker** [comment]
Hi,

This is actually intended behaviour. Instead, you'll want to use the (global-only) [exception](https://inertiajs.com/events#exception) event:
> The `exception` event fires on unexpected XHR errors, such as network interruptions, and for errors generated in the `resolveComponent()` callback.

The reason this isn't caught within the `onError` event, is because the `onSuccess` and `onError` events are only used to distinguish whether the _Inertia page visit_ was completed without (validation) errors or not.

Hope this helps!

**Comment by Archheretic** [comment]
I see. My problem is that if this request fails I want to give the user the option to retry the failed request. In a global exception event handler it's harder to pick out what exactly failed.

I could use axios directly instead of Inertia, but in this scenario I want to give the client fresh data on success. So if I use axios on the initial request I would need to do an extra request with intertia after confirming that everything went well.

**Comment by claudiodekker** [comment]
Alright, but since with Inertia the state isn't changed until the server returns a new/updated state, can't you use the `exception` event to display a message requesting them to try again after a few moments? That's what is was designed for. 

You're right that as of right now it's pretty much impossible to automatically retry the request. This is admittedly mostly done on purpose (most events are available as callbacks) because whenever situations like these occur there's too many uncertainties, and generally this makes it something that you probably don't want to automate.

For instance, imagine you're submitting a create/POST call that creates a new comment, but the network disconnects, or some internal server error occurs that closes the connection from the server-side. Whenever this happens, you can't know for certain that the server didn't process the request already. 

It could be that the action was already performed, but the _response_ simply wasn't fully received by the client side yet. Similarly, it could also be that the server never received the request. In the first situation, you'll end up with no posts in the database at all, but in the second situation, you could end up with tons of duplicate database entries without the user fully understanding _why_, while there aren't any apparent bugs in the code.

Anyway, we could consider introducing it as a local event, but honestly I'm not sure if I'd personally want to support this use-case for those reasons above. What do you think, @reinink?
