### ISSUE TITLE
Unique email validation error

### ISSUE THREAD

**Issue by lucasantoniooficial** [inertiajs/inertia#634]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

The problem is in the validation of inertia, when I do a validation of Unique in which I did the test it does not return the error correctly.

### Steps to reproduce:

Have a bank record with existing email and have a formRequest with required | unique: users email validation.

Access the form page with the validations already configured, as suggested by the documentation.

Fill in the data with the existing email and press the submit button.

The error does not appear.

Second reproduction that the error appears.

Access the form and submit without data, then fill in the data with the existing email.

**Comment by taylormaguire** [comment]
I'm having a similar issue. If i switch to `v-show` instead of `v-if` the error appears however. I also get this error in the console. Do you get the same console error with `v-if`?

`Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null`

**Comment by lucasantoniooficial** [comment]
> I'm having a similar issue. If i switch to `v-show` instead of `v-if` the error appears however. I also get this error in the console. Do you get the same console error with `v-if`?
> 
> `Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null`

Same thing with both v-if and v-show.

**Comment by lucasantoniooficial** [comment]
Is it a behavior expected by the creators of inertiajs? Or is it really a problem that affects the usability of the package?

Because it's okay for me to use v-show instead of `v-if`

**Comment by reinink** [comment]
So there has been tons of bug fixes since the `0.3.5` Vue 3 adapter. Are you able to upgrade to the latest version of Inertia, the Vue adapter and the Laravel adapter, and let me know if the problem persists? Please see the releases page for upgrade notes: https://inertiajs.com/releases. Fair warning, we made many changes the last few months, and some of them were reverted. 😅

**Comment by taylormaguire** [comment]
`@inertiajs/inertia-vue3: 0.3.13`
`@inertiajs/inertia: 0.8.7`
`inertiajs/inertia-laravel: 0.4.1`

It's happening for me on the latest versions. Any time i try to do a `v-if`, if validation fails the `div` tag showing the error will not render and i get 

`Cannot read property 'insertBefore' of null` error in the console. 

Interestingly enough this problem also carries over to other elements that use `v-if` that are unrelated to the validation if laravel sends back any validation errors. The validation errors do show in the Vue dev-tools and if i switch to `v-show` the error goes away and i can see the validation errors in the `div` tag.

the Initial page load i do not seem to have an issue with `v-if` on anything, it just seems to be the redirects back.

**Comment by taylormaguire** [comment]
For testing I created a brand new app using Jetstream, then upgraded Inertia to the latest versions. Added a very basic form with validation similar to the Inertia docs.

Intermittently the `v-if` does not show and the `Cannot read property 'insertBefore' of null error in the console.` error appears in console. The combination of page refresh and filling out one field results in a different outcome than a page refresh and just hitting submit with no typing in the inputs. 

https://github.com/taylormaguire/inertia-jet-test

![image](https://user-images.githubusercontent.com/18236969/115283214-ec825080-a0ff-11eb-9b50-083093dee599.png)

**Comment by claudiodekker** [comment]
Honestly, this sounds like it's an issue related to Vue 3, instead of an issue with Inertia, as the code you've provided (and it's entire stack trace, as shown in the screenshot), isn't used/called in Inertia (and likely is called _before_ that, as Inertia relies on Vue to be ready prior to initializing itself)

UPDATE: The same issue was discussed in #615, with the conclusion being that this was indeed a Vue bug with fragments that was seemingly fixed in Vue 3.1.5: 

- https://github.com/inertiajs/inertia/issues/615#issuecomment-886224383
- https://github.com/inertiajs/inertia/issues/615#issuecomment-823220799

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment so that GitHub will send me a notification of your response, at which point we can consider re-opening this issue.

Thanks!
