### ISSUE TITLE
`onError` callback naming is misleading.

### ISSUE THREAD

**Issue by pxlrbt** [inertiajs/inertia#643]
On Discord we figured out, that the `onError` callback for Inertia requests is a bit misleading.

A user tried to catch server side errors:

```js
submit() {
    this.form.put(this.route('emailModule.emails.update', this.email.id), {
      preserveState: true,
      onError: () => {
        console.log('error')
      }
    })
  }
 ```
> Why the onError isn't fired on abort(400)?

1. I already opened a [PR](https://github.com/inertiajs/inertiajs.com/pull/186) to clarify that behavior in the docs.
2. Maybe there is a better naming that indicated that the callback only is fired, when there are (validation) errors in the Inertia response.
3. Maybe this callback can be deprecated and be superseded by the Form helper?

**Comment by gajosadrian** [comment]
I would also have onError callback to handle server errors without modal. And show the modal error if the onError method isn't presented.

**Comment by reinink** [comment]
We seriously considered the callback `onValidationError()`, but it's quite long, and in reality, you generally shouldn't be checking for non-200 responses in your page components. Because of this, we decided to use `onError` for validation errors, realizing that this might be a little confusing at first. I have tried to explain this as best as possible on the validation page ([see here](https://inertiajs.com/validation#how-it-works)).

As a general rule, in an Inertia app, we believe that 400/500 series responses should be handled outside of page component code. Typically these result in either a modal, or if you've wired up your app's exception handler properly, a 400/500 Inertia error page ([see here](https://inertiajs.com/error-handling#production)).

This is one of the really nice things about working with Inertia, is that you don't need to be thinking about these kinds of errors in your page component code.

That all said, we have considered adding an `onException()` callback for these situations, just so you can do cleanup should an exception happen. However, generally speaking doing this in `onFinish()` is actually sufficient.

I hope that makes sense. 👍

**Comment by pxlrbt** [comment]
@reinink Thanks for clarification in the docs. I still think this would be better on the "Manual Visits" page, as this is where the `options` for visits are documented.

**Comment by reinink** [comment]
@pxlrbt Agreed 👍

**Comment by advename** [comment]
What's the status on `onException()` @reinink ?
I can't see how `onFinish(visit)` suffices during a server side exception, since `visit` contains no information that an exception has occured.

**Comment by advename** [comment]
Well, i just experimented with adding the `onException` callback, and I ran into several challenges that make it difficult to implement effectively.

As @reinink pointed out, InertiaJS is designed around the concept of server-driven web apps. For example:

* Validation is handled entirely on the server side. You define the rules once on the backend, and the server responds with any errors, which you then display in the frontend.
* When exceptions occur on the server, the backend is expected to render the appropriate response page—such as a generic 500 error page.

These design principles limit the usefulness of an `onException` callback. To make it work well, you'd need to adjust both your backend and your Inertia requests to return helpful error messages during development, and generic ones in production—without introducing breaking changes.

---

On a side note, while showing a generic "catch-all" error page might work in some cases, it's a harsh user experience and disrupts the flow. A better approach is to show a user-friendly notification indicating that an action failed due to a server-side error.

You *can* implement this by listening for exceptions globally, using something like:

```js
router.on('exception', () => {
  showNotification("Something went wrong.");
});
```

However, this approach also has limitations—it applies the same message everywhere, preventing you from tailoring feedback based on context. For instance, instead of a generic "Server error occurred," you'd ideally want to show something like "Failed to delete your post."

Because of these limitations, I've decided to only use `router` for page navigation going forward. For CRUD operations, I'll continue with axios and handle server validation error seperatly. And since `useForm` internally uses `router`, I'll switch to using `react-hook-form` instead.
