### ISSUE TITLE
Implementing Inertia incrementally

### ISSUE THREAD

**Issue by davidhan527** [inertiajs/inertia#659]
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-react` version: 0.5.12

### Describe the problem:

First of all, thank you for such a great library! This is the missing piece to front-end routing that I've always been looking for!

I'm trying to implement Inertia incrementally on my app that's using React + Rails.

When I'm on a page where Inertia was initialized at the root level (using the snippet below), clicking InertiaLink's work as expected.

```
      <App
        initialPage={JSON.parse(el.dataset.page)}
        resolveComponent={(name) =>
          import(`./pages/${name}`).then((module) => module.default)
        }
      />
```

However, when I'm on a page where Inertia hasn't been initialized yet, the InertiaLink won't fall back to the previous behavior where we visit the page without using XHR. 

Here is the error that I get:

```
index.js:435 Uncaught (in promise) TypeError: this.resolveComponent is not a function
    at Object.setPage (index.js:435)
    at index.js:369
```

Is it possible to have InertiaLink fallback to non-Inertia behavior if Inertia is not initialized at the React root level, is there a different approach you would suggest for implementing Inertia incrementally? I imagine that most medium-large applications will have trouble rewriting every root page in order to start using this library.

Thank you for your help!

**Comment by tyler-shaw** [comment]
Did you end up finding any kind of solution for this? I've been wondering the same thing.

**Comment by davidhan527** [comment]
The workaround I used was to implement Inertia in multiple phases.
1. Convert all root pages to render as Inertia pages.
2. Convert links to Inertia links.

**Comment by reinink** [comment]
@davidhan527 Yup, that's exactly the approach I'd recommend.

1. Upgrade one page at a time, but don't start using Inertia links until everything has been converted, otherwise you'll run into issues while linking from non-Inertia pages. It means full page reloads until then, but that's fine in the interim.
2. Once everything has been converted to Inertia (Vue/React/Svelte) pages, then go in and add Inertia links.

The only tricky thing here is when you submit forms, as the recommended approach is to redirect to another Inertia page on success. You could still do that, and add a middleware that automatically returns a "location" visit for all non-Inertia endpoints to force a full page visit client-side. See "external redirects" for more information: https://inertiajs.com/redirects#external-redirects
