### ISSUE TITLE
Upgrade to 0.4 breaks the app

### ISSUE THREAD

**Issue by plakhin** [inertiajs/inertia#702]
### Versions:

- `@inertiajs/inertia` version: 0.9.0
- `@inertiajs/inertia-vue3` version: 0.4.0

### Describe the problem:

I have a Laravel 8 + Vue3 web app that uses persistent layouts with default layouts. After upgrading inertia to 0.9.0, inertia-vue3 to 0.4.0 and inertia-laravel to 0.4.2, I'm getting `[Vue warn]: Component is missing template or render function.` error on every page. Some simple pages still work, but more complicated pages fails to load at all with a lot of errors (see screenshot).

![image](https://user-images.githubusercontent.com/25561058/120128096-d33aec80-c1f3-11eb-8507-6da6c3a16b26.png)

I guess this may be related to https://github.com/inertiajs/inertia/commit/fb4b559a5b8e10409b749f0ad4be52f917e0fe75 but not sure. I didn't find any "upgrade guide" to inertia 0.9 / inertia-vue3 0.4 and still can't solve the issue.

**Comment by reinink** [comment]
So, without seeing the code that actually generates these errors, it's very hard to diagnose what's going wrong. I have not seen these errors myself in my Vue 3 apps on the latest versions.

My recommendation:

1. Delete your `node_modules` folder.
2. Upgrade to the latest version of `@inertiajs/inertia` and `@inertiajs/inertia-vue3` (there have been minor releases since).
3. Upgrade to the latest stable version of Vue 3.
4. Run your build again.

If that doesn't work, please provide a simple demo app that reproduces this issue, and I'll look into this deeper.

**Comment by plakhin** [comment]
@reinink thanks for response!
I've managed to fix broken app by fixing few components, but still getting `[Vue warn]: Component is missing template or render function.` warning. Will try your suggestion.

**Comment by jatinthapar1910** [comment]
Same error with me.
