### ISSUE TITLE
Redirect with hashtag from server gets stripped in InertiaJS

### ISSUE THREAD

**Issue by Cannonb4ll** [inertiajs/inertia#729]
### Versions:

- `@inertiajs/inertia` version: 0.9.1
- `@inertiajs/inertia-vue` version: 0.6.1

### Describe the problem:

I have a Laravel app, where I want to redirect with a hashtag (e.g. example.com/page#hash) but the hashtag gets stripped.

It seems this is the line preventing hashtags to come along:

https://github.com/inertiajs/inertia/blob/master/packages/inertia/src/router.ts#L275
https://github.com/inertiajs/inertia/blob/211f49b98928b0f5f366387b6fbf99a65e4a07be/packages/inertia/src/url.ts#L42

Is it possible to allow hashtags? Might be cool if this would be configurable, like:

```js
this.$inertia.post('/url', {foo: bar}, {allowFragments: true});
```

### Steps to reproduce:

In a Laravel app, do:

```php
return redirect()->route('my-page', '#hash');
```

Or:

```php
return redirect()->route('my-page')->withFragment('hash');
```

And see results in InertiaJS, in default Laravel + Blade it works fine, the hashtag remains in the URL.

**Comment by aidan-casey** [comment]
Inertia uses the Laravel `getRequestUri()` method for the URL included in the [response](https://github.com/inertiajs/inertia-laravel/blob/master/src/Response.php#L92). By default, it does not look like PHP maintains the URL fragment in the server variable, but Symfony's HTTP Foundation (which Laravel uses under the hood) also especially strips out the URL fragment [here](https://github.com/symfony/http-foundation/blob/d8037fef55120a55a5faf39f8375609356459cae/Request.php#L1812).

It seems like we would have a difficult time actually getting the hash into the URL sent back to the client. I'm also not sure how worth it is, since we can use traditional routing, etc. with Inertia.

**Comment by Cannonb4ll** [comment]
@aidan-casey If you use a default laravel app with blade, my code works just like you expect it to work.

How would you explain that?

**Comment by aidan-casey** [comment]
In a traditional Laravel + Blade app, the server returns a redirect response with a Location header. The browser then sends the request to the URL specified in the Location header (which would include the URL fragment). There's nothing funky going on here and it is working as the browser should.

In the case of Inertia, it's not being made aware of the Location URL (with the hash) because it is utilizing Axios under the hood which is just following the redirect. Inertia is then updating the current URL and browser history with the URL in the JSON Inertia response from Laravel (which doesn't include the fragment).

In order to get this working, Inertia technically needs to intercept the redirect response, store the hash fragment client side, make the request to the destination, and finally append the hash back onto the URL once done as it does with normal visit requests without a redirect.

**Comment by dima-bzz** [comment]
@claudiodekker Hello. I wanted to ask about the behavior when there is an anchor in the url. There is a page `http://localhost/admin/settings#main` and it has a settings form. When I save the form `this.form.post('http://localhost/admin/settings/main')`, the anchor is removed from the page url. That is how it should be?

**Comment by aidan-casey** [comment]
@dima-bzz - That is correct.

**Comment by dima-bzz** [comment]
@aidan-casey So I can't save the anchor?

**Comment by claudiodekker** [comment]
Not right now, that's what the issue is about ;)

**Comment by dasundev** [comment]
@sarukomine Many Thanks!

**Comment by joao-antonio-gomes** [comment]
Any perspective to add this behavior to inertia?
