### ISSUE TITLE
Module '"@inertiajs/inertia-vue3"' has no exported member 'createInertiaApp'.

### ISSUE THREAD

**Issue by dacoto97** [inertiajs/inertia#755]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.7

### Describe the problem:

Typescript error: Module '"@inertiajs/inertia-vue3"' has no exported member 'createInertiaApp'.

### Steps to reproduce:

Create app.ts and import createInertiaApp from @inertiajs/inertia-vue3

```
import { createInertiaApp, usePage } from "@inertiajs/inertia-vue3"

createInertiaApp({
    ...
})
```

**Comment by ycs77** [comment]
PR #742 will solved this problem... 😉

**Comment by jatinthapar1910** [comment]
Same problem with me. 
Is this available on `0.4.7` ?

**Comment by bebetoalves** [comment]
Same problem here... :/

**Comment by bebetoalves** [comment]
> Same problem with me.
> Is this available on `0.4.7` ?

Yeah it's not available yet 😢

**Comment by dacoto97** [comment]
We must wait for a release higher than 0.4.7, since it was published before this fix.

**Comment by reinink** [comment]
These have been released as `@inertiajs/inertia-vue@0.7.0` and `@inertiajs/inertia-vue3@0.5.0`. However, please note that these are breaking releases, since we removed the automatic registration of the Inertia link and head components ([see here](https://github.com/inertiajs/inertia/pull/765)). That PR explains how to manually register those components globally, if you do want to upgrade to these latest versions. 👍

**Comment by dacoto97** [comment]
You are right, the problem is the definition of Typescript. I'm going to do a PR to add this definition.

**Comment by Giesch** [comment]
It looks like this function is missing from the react declarations as well.

**Comment by reinink** [comment]
@Giesch Yup, we don't maintain any of the type files in the adapters. We're hoping to eventually convert the adapters to TS proper.
