### ISSUE TITLE
AngularJS adapter

### ISSUE THREAD

**Issue by ezp127** [inertiajs/inertia#81]
Hi everyone,

Is there any possibility for Inertia to provide an AngularJS(1.x) adapter? 

Unfortunetly at the moment I don't have knowledge enough to make such adapter, but would use it for sure.

Maybe Jonathan could make a little poll so we can see if other developers also have interest.

**Comment by Juhlinus** [comment]
Hello @ezp127 !

I don't think a poll is needed. If there's someone who's interested then I think that alone justifies there being an adapter.

However, we need the help of someone who's familiar with Angular in order to help us build an adapter. 😄

**Comment by reinink** [comment]
> However, we need the help of someone who's familiar with Angular in order to help us build an adapter.

Bingo! 😊

It's basically impossible for us, the core library maintainers, to create all the possible adapters. It would require being experts in every possible language and framework. Instead, we're relying on experts in those languages and frameworks who are interested in using Inertia.js to build these adapters.

I am planning to write a server-side adapter "how to" soon. 👌

**Comment by zakiaziz** [comment]
@reinink Wondering if you ever wrote up a "how to" for this?

**Comment by hettiger** [comment]
Hi @reinink

I've tried to build an Angular 2 adapter today. I might be able to help. However I've looked into the existing 1st party adapters and theres a lot of detail stuff going on. I think it would be great if my adapter could build on the core as well. Are you planning on writing a frontend adapter "how to"? That'd be awesome.

Here's what I've come up with so far:

https://twitter.com/martinHettiger/status/1685248858396188672?s=20

Best regards,
Martin

**Comment by reinink** [comment]
@hettiger hey no official plans to support Angular at this time — even if you were able to create it, if it became official it would mean that I'd need to maintain it moving forward, and unfortunately I've never worked with Angular so that would be difficult for me to do.

Also, unfortunately no client-side adapter guide exists — really your best bet is to look at the existing adapters and try to figure out what's going on.

Sorry I can't be more helpful — I love that you're interested in the project, but I think if you're going to create an Angular adapter it's going to have to remain third-party at this time.

Hope that makes sense 🙏

**Comment by hettiger** [comment]
Hi @reinink 

thank you for the kind words. I can totally understand that you don't want to make this a first-party adapter.
Would it be OK for you if I ask further questions regarding the core?

Best regards
Martin

**Comment by reinink** [comment]
@hettiger yeah hit me up — I'll do my best to answer 😊
