### ISSUE TITLE
Module '"@inertiajs/inertia-react"' has no exported member 'Head'.

### ISSUE THREAD

**Issue by geocfu** [inertiajs/inertia#824]
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-react` version: 0.7.0

### Describe the problem:

As the title implies, there is no exported Head member from inertia-react. Also, react types.d.ts don't have it as well.

### Steps to reproduce:

Follow the Title & meta installation instructions from inertia.js

**Comment by geocfu** [comment]
@reinink @claudiodekker 
I am kindly bumping this, since I think it's important for anyone using typescript. Essentially, if anyone is using typescript with react, they can't use the Head component.

**Comment by claudiodekker** [comment]
Hi @geocfu,

While I understand that this issue has a vast importance to you and possible others that use the Head component with React, there simply put isn't much we can do to speed things up to a point where we can get this issue done faster.

I started writing a very long, multi-pointed post describing why things aren't going as fast as we'd wish, but instead of posting that, I think it's better to just reduce the scope as to why this issue isn't being worked on:

- Both @reinink and I are currently quite busy right now. Jonathan's working on the Inertia course, and I'm working on some unrelated Laravel work that causes me to have too little time (without risking a burnout) to work on Inertia right now (I do hope this changes very soon).
- We're considering this issue already being worked on as part of 'blanket' change, as we're working on converting the entire Inertia codebase to TypeScript, including the React adapter. Once that's done, this issue will be automatically fixed as well.
- Apart from @reinink and I, there isn't really anyone else who's consistently helping out with adding relevant changes. While I really appreciate the PR's submitted by the community, they're often either to (unexpectedly) introduce new features, or are from first-time contributors, meaning that because we don't know the person's experience/style/considerations, we have to carefully review the PR's instead of being able to for the most part trust their contributions. This unfortunately means that we often spend almost more time reviewing things than it would take us to implement the change ourselves. Alternatively, we'd have to rejecting the PR'd change by writing the reasons for doing so in a polite way that doesn't insult the person or their efforts. While I'm already giving this point way too much weight in this example, there's way way way more to say about the reasons for open-source working the way it does it if I were to explain things properly.

With that said, is there no way you can ts-ignore the import? or cast it to an 'any' or 'unknown' type? If not, feel free to submit a PR for this. 

In either case, while I appreciate that you're letting us know it's important, please note that our inactivity on this matter does not mean we're not aware of it and it's importance; We're simply too busy getting other also-important/already-in-progress things done before we can get around to fixing issues such as these.

Hope this explains!

**Comment by geocfu** [comment]
I completely understand your point.

I will follow your guidance on the matter. 
Also, I will keep this issue updated with the achieved results, so others can benefit as well.

Thank you.

**Comment by danielbrodin** [comment]
A PR for this exists here #855

**Comment by FahriDevZ** [comment]
I've been waiting for this for weeks.
I think the PR should be merged, it's so weird when i see @ts-ignore in my code.

Thanks you.

**Comment by TitasGailius** [comment]
See https://github.com/inertiajs/inertia/pull/855#issuecomment-922733920 for a temporary workaround.
