### ISSUE TITLE
Reframe + Inertia.js = <3?

### ISSUE THREAD

**Issue by brillout** [inertiajs/inertia#83]
Hi @reinink,

I really like what you are building here.

I'm doing something similar with [github.com/reframejs/reframe](https://github.com/reframejs/reframe), [github.com/reframejs/goldpage](https://github.com/reframejs/goldpage), and [github.com/reframejs/wildcard-api](https://github.com/reframejs/wildcard-api).

While Reframe only supports a Node.js backend, Inertia.js supports Rails and Laravel. But other than that we are building something similar; on a high-level we are both frontend framework + RPC.

Would you be up to join forces?

**Comment by reinink** [comment]
Hey @brillout! Thanks for your interest in Inertia.js. That's cool to hear we're doing similar things! At this point I'm not sure I'm in a position to go down a project merge path...mostly because the Inertia.js name is well established already, and frankly, I don't have the time. That said, you are, of course, more than welcome to contribute to this project (ie. create a Node.js adapter).

Best of luck! 👍

**Comment by AyoAlfonso** [comment]
If someone were to build this Node.js adapter, how would one go about it ?

**Comment by Juhlinus** [comment]
Hello @AyoAlfonso !

You can check out the protocol page of the documentation here:

https://inertiajs.com/the-protocol
