### ISSUE TITLE
rememberedState of undefined - React

### ISSUE THREAD

**Issue by yashiroiori** [inertiajs/inertia#866]
### Versions:

- `@inertiajs/inertia` version: ^0.10.1
- `@inertiajs/inertia-react` version: ^0.7.1

### Describe the problem:
Try use useRemember hook but return error "rememberedState of undefined"

### Steps to reproduce:
Into component try use an example displayed in section "Remembering state"

![image](https://user-images.githubusercontent.com/17031855/129791936-0f98ce71-a440-40a2-b66d-cb0b56f46329.png)

Error
![image](https://user-images.githubusercontent.com/17031855/129792004-a367db90-4a9c-4769-9f99-2febe606eead.png)

**Comment by BjornDCode** [comment]
We experienced the same issue so I did some digging. It only happens on the first page load. If I navigate to the page using `useRemember` from another page it loads fine. 

The issue appeared when we switched from the old rendering method (directly rendering App) to using `createInertiaApp`.

It appears the `useRemember` hook runs before Inertia is initialised. `useRemember` calls `Inertia.remember` internally.  The `remember` method relies on `this.page` being set on the Inertia instance. This happens when the `init` method is called, which happens in `createInertiaMethod`. When I log from `useRemember` and `init` it seems like `useRemember` is called before the `init` method.

<img width="658" alt="Screenshot 2021-08-31 at 13 16 50" src="https://user-images.githubusercontent.com/14328774/131493396-72655d50-0897-4895-82e9-61824b15cfbe.png">

**Comment by yashiroiori** [comment]
> We experienced the same issue so I did some digging. It only happens on the first page load. If I navigate to the page using `useRemember` from another page it loads fine.
> 
> The issue appeared when we switched from the old rendering method (directly rendering App) to using `createInertiaApp`.
> 
> It appears the `useRemember` hook runs before Inertia is initialised. `useRemember` calls `Inertia.remember` internally. The `remember` method relies on `this.page` being set on the Inertia instance. This happens when the `init` method is called, which happens in `createInertiaMethod`. When I log from `useRemember` and `init` it seems like `useRemember` is called before the `init` method.
> 
> <img alt="Screenshot 2021-08-31 at 13 16 50" width="658" src="https://user-images.githubusercontent.com/14328774/131493396-72655d50-0897-4895-82e9-61824b15cfbe.png">

I try using Inertia.remeber and it's same error

**Comment by BjornDCode** [comment]
@yashiroiori Oh yeah, to be clear I never found a solution. Just wanted to share what I discovered

**Comment by mrtijn** [comment]
Made a pr to fix this.
+ some other changes

https://github.com/inertiajs/inertia/pull/949
