### ISSUE TITLE
Bug: Cannot scroll to top manually in inertia apps

### ISSUE THREAD

**Issue by haikyuu** [inertiajs/inertia#880]
I tested in [the official ping crm](https://demo.inertiajs.com) as well as in an app I'm working on.

Basically, to reproduce it open the console and run `window.scrollTo({ top: 0, behavior: 'smooth' });`

It works in other websites just fine.

Thank you

**Comment by schniper** [comment]
Would need this: the idea would be to be able to scroll to top in case of POST validation errors.

**Comment by reinink** [comment]
So the reason this doesn't work in the Ping CRM demo app is because the app uses a scroll container. If I had to rebuilt it, I could have made the whole body scrollable when scrolling the content, in which case this would work. You could, of course, manually scroll the content scroll container.

Either way, this is totally possible, the implementation just changes depending on how you've built your app.

Hope that helps. Closing this as it's not an Inertia.js bug. 👍
