### ISSUE TITLE
issue with append the value to the element using useform

### ISSUE THREAD

**Issue by anjvelu** [inertiajs/inertia#893]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-react` version: 1.2.0

### Describe the problem:

I have a basic login form with username and password along with google invisible ReCaptcha version 3. From recaptcha docs reference the token is valid for 2 mins. So, i am generating the token and append it while submitting the form.

### Steps to reproduce:

Here is my code.
```javascript
const { data, setData, post, processing, errors, reset, transform } = useForm(
    {
      email: "",
      password: "",
      gRecaptcha: "",
    }
  );
  const submit = (e) => {
    e.preventDefault();
    await callToken();
    post(route("login"), {
      onError: (error) => {
        notifyError();
      },
    });
  };
const recaptcha = new gReCaptcha3("login");
const callToken = async () => {
  let t = await recaptcha.getToken();
  //console.log(t);
  setData("gRecaptcha", t);
};
```
when I submit the form the 1st time, the token wouldn't send along the form. So, I tried some other way like,
```javascript
 const callToken = async () => {
    let t = await recaptcha.getToken();
    //console.log(t);
    setData("gRecaptcha", t);
    transform((data) => ({
      ...data,
      gRecaptcha: t,
    }));
  };
```
No luck. Please suggest to me, the way of sending the token along with the form data.

**Comment by anjvelu** [comment]
Expected async state. But, could not achieve it by current react inertia. Solved my use case using effect hook with little code change. 
```javascript
const [doSubmit, setDoSubmit] = useState(false); 
const submit = (e) => {
    e.preventDefault();
   callToken();    
   setDoSubmit(true);
  };
const callSubmit =() => {
    post(route("login"), {
      onError: (error) => {
        notifyError();
      },
    });
}
useEffect(() => {
  if(doSubmit){
    callSubmit();
    setDoSubmit(false);
  }
});
```
Please let me know if this causes any issues.

**Comment by reinink** [comment]
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️
