### ISSUE TITLE
Raw object data shown instead of render the component

### ISSUE THREAD

**Issue by caktoy** [inertiajs/inertia#900]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-react` version: 0.7.1

### Describe the problem:

I develop web application using Laravel-Inertia-React, everything work well, but when I access my web pages from mobile browser and minimize for a while, then I open the browser again it shown the raw object data component instead of render the component. When I refresh the page it turn normal again and render the page normally.

![photo1631665146](https://user-images.githubusercontent.com/6917446/133350779-e9365f3f-aaca-43d0-b68c-777038974e98.jpeg)

### Steps to reproduce:

My code is just like at the documentation, no specific differences, only the behaviour I didn't expected.

**Comment by inlogicstudio** [comment]
Clear your application cache and repeat the process to see if it still happens like.

**Comment by caktoy** [comment]
Can I do this manually? If so, what files/folders should I delete to clear my app cache? because I deploy my application on shared hosting with limited access.

**Comment by inlogicstudio** [comment]
Ask your host company if you can have access to terminal

**Comment by inlogicstudio** [comment]
Also you can try to delete all the build files and rerun the build again i just felt this has nothing to do with inertia

**Comment by inlogicstudio** [comment]
> Can I do this manually? If so, what files/folders should I delete to clear my app cache? because I deploy my application on shared hosting with limited access.

https://laravel.com/docs/8.x/artisan#programmatically-executing-commands

**Comment by RobertBoes** [comment]
There was a similar issue to this, but I can't seem to find it.

The reason this is happening is because Chrome caches the last request. When you click on an Inertia link, the last request that was made has a request header `Accept: text/html, application/xhtml+html` and a response header with `Vary: Accept`, but the response contains JSON. Chrome then caches that as the actual page, so when it "resumes" the page after a while it will load that JSON response from cache.

**Comment by inlogicstudio** [comment]
Is your own case react as well

**Comment by caktoy** [comment]
I believe my inertia setup was fine, and also react as well, nothing wrong with it, it's just like @RobertBoes said, I think it's about browser cache. I don't know how to prevent the browser to load the JSON instead of render the page. I was clear the cache in the laravel side, but the problem still occur.

**Comment by inlogicstudio** [comment]
hmmm check if your assets is versioned 

https://laravel.com/docs/8.x/mix#versioning-and-cache-busting

**Comment by caktoy** [comment]
I did it, in my weback-laravel-mix configuration for asset versioning was activated

**Comment by inlogicstudio** [comment]
Alright since the issue still persist can you provide a link to the live application  or some kind elaboration to help @reinink properly take a look at it including any other info that can help..

**Comment by ericsssan** [comment]
https://github.com/inertiajs/inertia/issues/154

Similar issue. 

Does it happen on local? Try with another hosting? Firebase hosting is free for testing.

**Comment by caktoy** [comment]
@inlogicstudio 

http://test.memb3r.com/ 

that's my live application URL

**Comment by inlogicstudio** [comment]
this link is not loading up at all

**Comment by claudiodekker** [comment]
Hey,

So, under normal circumstances this would indeed be caused (as @RobertBoes already mentioned) by the `Vary: Accept` header not being present. [This HTTP header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.44) tells the browser that there's two different copies of the same content at the same URL, and helps it to determine whether and when the response should be cached. 

However, it's pretty normal for Mobile apps to 'freeze' memory and do other kinds of optimizations to prevent battery drain in the background (especially with javascript-heavy browser tabs), so **I suspect** that when you re-open your browser, it quickly 'restores' the browser tab with the state it had cached, which for some reason is JSON instead of your JS-rich HTML/Vue app. **If this is the case, then this looks like it's a bug in your mobile browser related to it caching the wrong request**.

Unfortunately, I don't think there's a lot we can really do about this. The only thing I could recommend trying is the following to confirm whether this is indeed the case, or whether we're looking at a different issue altogether:
- Attach a debugger to the mobile browser, so that you can look at the requests that are being made
- Then, save the request data of these requests to a file (so we can inspect them in detail if needed)
- Next, reproduce your issue again by background the browser. If you're not able to reproduce it, try again, but each time make sure to save the request data of those requests, so that once it's reproduced, we can go back to the request data and figure out exactly what happened between the server and browser when the issue occurred.
- Finally, once reproduced, look at the requests you saved, and ensure that the server was indeed sending all the required headers (one or two people have reported similar issues on desktop in the past, where it ended up being caused by a proxy or the server stripping headers that Inertia requires). 

If you've done the above, and you're either unable to tell or don't know what to look for, feel free to share this request data [as a gist](https://gist.github.com), and comment it as a reaction to this issue, so that we can take a closer look at exactly what's going on.

Until then, given that you mentioned that everything works fine until you background the browser, as well as that I can't think of anything that Inertia does that could cause this (it doesn't do anything 'by itself' and always requires user input to do something), I'm fairly confident that this isn't an Inertia issue but is instead a browser issue (as mentioned earlier), and as such will close this issue for now.

If you have more information about this, or if you are absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Comment by alexandreguichet** [comment]
@claudiodekker Hi, it seems I have the issue as well.

<img width="912" alt="Screen Shot 2022-06-25 at 7 48 45 PM" src="https://user-images.githubusercontent.com/37989302/175784957-4bcf1b92-9bad-4055-bd58-404c0c4f926d.png">

I am on a local environment on a Macbook and this happens for both Chrome and Safari, all the time. I've tried all above fixes without success. Any ideas on what might cause the issue?

**Comment by aobozhang** [comment]
My Case:
```
"@inertiajs/inertia": "^0.11.0",
"@inertiajs/inertia-vue3": "^0.6.0",
```
 it shown the raw object data component instead of render the component when I use "back" from specific pages.

My reason:
I made a mistake in using few <a> instead of <Link> component in template someplace.
When A link clicked, The target page would not be able to back with inertia render

**Comment by mdmaruf782** [comment]
same issue.. is it resolved?

**Comment by awanishnathpandey** [comment]
Still same issue till date. When I duplicate the window it do not render the page but only shows the JSON data

**Comment by darkylmnx** [comment]
@claudiodekker  This issue occurs on my app on Chrome on a mac.
It only happens on my app and not on Inertia's website using the same browser on the same machine.

When looking into the details of my app, I don't see any particular HTTP header that would cause that.

Others seem to also still have the issue.

**Comment by Maneal689** [comment]
I still have the same issue on Chrome Windows and MacOs too, is there any resource on how to fix this ?

**Comment by michel-garcia** [comment]
@Maneal689 Can you check if the Inertia middleware is properly set up in your project? Go to [Server-side setup - Inertia.js](https://inertiajs.com/server-side-setup#middleware), and follow the steps under the section _Middleware_. This middleware sets the `Vary` http header which is necessary for Inertia requests not to be cached.

**Comment by Maneal689** [comment]
> @Maneal689 Can you check if the Inertia middleware is properly set up in your project? Go to [Server-side setup - Inertia.js](https://inertiajs.com/server-side-setup#middleware), and follow the steps under the section _Middleware_. This middleware sets the `Vary` http header which is necessary for Inertia requests not to be cached.

I just verified, it's already set on my app/Http/Kernel.php -> protected $middlewareGroups = ["web" => [..., \App\Http\Middleware\HandleInertiaRequests::class]]

Project initialised with
Laravel 10 then upgraded to 11
@inertiajs/vue3 ^1.0.15
inertiajs/inertia-laravel  ^1.0

**Comment by michel-garcia** [comment]
Laravel 11 should be able to pick up the old file structure just fine but I still believe that the Inertia middleware is not being registered correctly. What happens if you try registering it in `bootstrap/app.php` like in the docs I linked before?

**Comment by Maneal689** [comment]
It is the way described for laravel 10 : https://web.archive.org/web/20240101031851/https://inertiajs.com/server-side-setup

My bootstrap/app.php looks like this, and function "withMiddleware" doesn't exists on class Illuminate\Foundation\Application :

```
<?php

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Laravel application instance
| which serves as the "glue" for all the components of Laravel, and is
| the IoC container for the system binding all of the various parts.
|
*/

$app = new Illuminate\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

/*
|--------------------------------------------------------------------------
| Bind Important Interfaces
|--------------------------------------------------------------------------
|
| Next, we need to bind some important interfaces into the container so
| we will be able to resolve them when needed. The kernels serve the
| incoming requests to this application from both the web and CLI.
|
*/

$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

/*
|--------------------------------------------------------------------------
| Return The Application
|--------------------------------------------------------------------------
|
| This script returns the application instance. The instance is given to
| the calling script so we can separate the building of the instances
| from the actual running of the application and sending responses.
|
*/

return $app;
```

**Comment by michel-garcia** [comment]
I have multiple Laravel 11 projects running Inertia, this issue only occurs if I remove the middleware. Can you check if your Inertia responses have the `Vary` header set?

**Comment by Maneal689** [comment]
On page load/reload I have "Vary: Accept-Encoding" on response headers
On client navigation/XHR request I do not

**Comment by hellohasan** [comment]
> Still same issue till date. When I duplicate the window it do not render the page but only shows the JSON data

brother did you get the solution

**Comment by magnokf** [comment]
So the issue cames from the hosting provider?
I'm facing this unexpected result , and still don't know how to fix or prevent it.
Can anyone please help?

**Comment by magnokf** [comment]
So if the issue cames from the hosting provider and facing this unexpected result , you can prevent it modifying .htaccess file.

Add this piece of code to it.
#####

<IfModule mod_headers.c> 
<FilesMatch ".(js|css|xml|gz|html)$"> Header append Vary: Accept-Encoding
 </FilesMatch>
</IfModule>

####

Hope it will help

**Comment by magnokf** [comment]
So if the issue cames from the hosting provider and facing this unexpected result , you can prevent it modifying .htaccess file.

Add this piece of code to it.
#####

<IfModule mod_headers.c> 
<FilesMatch ".(js|css|xml|gz|html)$"> Header append Vary: Accept-Encoding
 </FilesMatch>
</IfModule>

####

Hope it will help

**Comment by magnokf** [comment]
#<IfModule mod_headers.c> 
<FilesMatch ".(js|css|xml|gz|html)$"> Header append Vary: Accept-Encoding
</FilesMatch>
</IfModule>#

**Comment by AyourElwazani97** [comment]
i had same issue but fixed when adding 
<IfModule mod_headers.c>
    Header add Vary "X-Inertia"
</IfModule>
to my .htaccess

**Comment by MedtheVorg** [comment]
My app is deployed on a shared-hosting platform, and disabling cache entirely for any x-inertia request fixed the issue for me.

@AyourElwazani97 I tried your fix but it did not work for me, but ultimately made me search further and find my own solution.


To fix the issue I added this code to the .htaccess file : 

```apache
<IfModule mod_headers.c>
    # Only disable caching for requests WITH X-Inertia header
    Header always set Cache-Control "no-cache, no-store, must-revalidate" env=HTTP_X_INERTIA
</IfModule>

**Comment by AyourElwazani97** [comment]
@MedtheVorg totally agree also i was deploying it in hostinger shared hosting and the problem was that CDN that hostinger uses, when i disable the CDN it worked perfectly

**Comment by camilobv** [comment]
> My app is deployed on a shared-hosting platform, and disabling cache entirely for any x-inertia request fixed the issue for me.
> 
> [@AyourElwazani97](https://github.com/AyourElwazani97) I tried your fix but it did not work for me, but ultimately made me search further and find my own solution.
> 
> To fix the issue I added this code to the .htaccess file :
> 
> <IfModule mod_headers.c>
>     # Only disable caching for requests WITH X-Inertia header
>     Header always set Cache-Control "no-cache, no-store, must-revalidate" env=HTTP_X_INERTIA
> </IfModule>

This worked for me
