### ISSUE TITLE
Unable to navigate to client-side-only route using Route::inertia()

### ISSUE THREAD

**Issue by wonder95** [inertiajs/inertia#905]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5
-  `inertiajs/inertia-laravel` version: 0.3.5

### Describe the problem:

According to the [Inertia docs](https://inertiajs.com/routing), if I want to have a Vue component that is not tied to a Laravel controller, I can define my route like so:
```
Route::inertia('/about', 'AboutComponent');
```

However, when I do that, I get the following error:
```
Error: Cannot find module './[object Object]'
```
However, if I just use a `Route::get` and return dummy content, like so:
```
Route::get('about', function() {
    return Inertia::render('AboutComponent', [
        'foo'=> 'bar'
    ]);
});

```

it works fine.

### Steps to reproduce:

1. Create Vue component in desired location.
2. Define route in `web.php` as described in docs:
```
Route::inertia('/about', 'AboutComponent');
```
3. Navigate to URL (`/about` in this case)
4. See error in console (none generated in `laravel.log`)

**Comment by dillingham** [comment]
@wonder95 I just tried it and it worked.. but it was an existing component within the resolve path:

resources/js/app.js

```
resolve: (name) => require(`./Pages/${name}.vue`),
```
```php
Route::inertia('/about', 'AboutComponent');
```
Would mean you have a component:
```
resources/js/Pages/AboutComponent.vue
```

**Comment by claudiodekker** [comment]
Hey @wonder95,

This is indeed likely related to the resolver not being able to find the component properly as @dillingham already suggested, and not as much with the server-side routing or Inertia specifically. 

While I do want to make this problem a bit more 'clear' (https://github.com/inertiajs/inertia/issues/710), this unfortunately looks like it's a configuration/application error on your end, and not as much a problem with in itself, so I'll be closing this issue for now.

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Comment by todaycodemaster** [comment]
I wanna know one thing.
Vue is SPA but as I feeling, if I use the inertia router, the whole page are reloading.

To protect it, should I use only  Axios?

And another question is can I navigate the component without controller?
