### ISSUE TITLE
Add Dialogs to Vue 3 adapter

### ISSUE THREAD

**Issue by claudiodekker** [inertiajs/inertia#932]

**Comment by pjhartin** [comment]
🙏 Please release early!

**Comment by quelo83** [comment]
Yes, this is a very important missing thing in InertiaJs. This feature makes everything easier and better!
I can't wait to use it!!!

**Comment by Wulfheart** [comment]
Maybe a release just for Vue3?😇

**Comment by oliverbj** [comment]
Any updates on this feature? :)

**Comment by andrewizmaylov** [comment]
Just watched a YouTube video about this Dialog feature. It's really cool! I'm waiting for it!

**Comment by Wulfheart** [comment]
@lepikhinb made package for it:
https://github.com/lepikhinb/momentum-modal

**Comment by SergejSi** [comment]
Urgently waiting for the feature. Is there already a release date for the feature?

**Comment by dwainscheeren** [comment]
Any updates on this feature?

**Comment by Wulfheart** [comment]
IIRC Taylor Otwell said that Inertia v3 would be released in the next two weeks.

**Comment by marciogaleno** [comment]
Inertia V3? But version 1.0 has not been released yet.

Em qui., 3 de nov. de 2022 às 11:09, Alex ***@***.***>
escreveu:

**Comment by Wulfheart** [comment]
Sorry. Confused the number with Livewire. I meant v1.

**Comment by marciogaleno** [comment]
But @reinink  is not responsible for inertia updates? What does Taylor Otwell have to do with it?

**Comment by bradjohns0n** [comment]
> IIRC Taylor Otwell said that Inertia v3 would be released in the next two weeks.

Two weeks have passed. Am I being impatient?

**Comment by Wulfheart** [comment]
Yes. 😂
It’s Open Source. Things take a little bit longer over here.

**Comment by dwainscheeren** [comment]
I now moved over to livewire unfortunately because modals/dialogs are a lot easier there.

**Comment by oliverbj** [comment]
I don't believe dialogs are a feature of Inertia v1.0. Hopefully with the new release, we'll soon see dialogs :)

**Comment by jaulz** [comment]
For anyone who's interested in a Vue3 solution, you can check my recent https://github.com/inertiajs/inertia/pull/642#issuecomment-1327498289 in the PR.

**Comment by Wulfheart** [comment]
This might also be helpful https://github.com/lepikhinb/momentum-modal.
cc @lepikhinb

**Comment by GoldenTypeAV** [comment]
Please tell me when it will be implemented? It would help a lot

**Comment by reinink** [comment]
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️
