### ISSUE TITLE
[bug] TypeScript definitions do not allow nested data on visits.

### ISSUE THREAD

**Issue by hailwood** [inertiajs/inertia#945]
Take the following request

```js
Inertia.get('/somewhere', {
  name: 'bob',
  prefs: {
    color: 'red',
    food: 'apple'
  }
})
```

This *does work* and will do a visit to `/somewhere?name=bob&prefs[color]=red&prefs[food]=apple`

Unfortunately the TypeScript definitions do not allow the nested object so we're forced to @ts-ignore it or deal with 
> TS2322: Type '{ color: string; food: string; }' is not assignable to type 'FormDataConvertible'.   Type '{ color: string; food: string; }' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 37 more.

**Comment by jjorissen52** [comment]
I will also point out that using a FormData object (which does appease the type hints) does not add the get parameters to the URL.

**Comment by Tofandel** [comment]
Issue is still there

Also arrays are not serialized properly when used in formData but objects are

Eg: `arr: [{test: 1, test2: 2}] => `arr[][test]=1&arr[][test2]=2` which in PHP will result in `[ 'arr' => [ ['test' => 1], ['test2' => 2] ] ]` instead of `[ 'arr' => [ ['test' => 1, 'test2' => 2] ] ]`

But an object `arr: {0:{test: 1, test2: 2}}` is serialized properly
