### ISSUE TITLE
In TypeScript Inertia payload can no longer be of type Array

### ISSUE THREAD

**Issue by Archheretic** [inertiajs/inertia#972]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: #.#.#
- `@inertiajs/inertia-vue3` version: #.#.#
- `@inertiajs/inertia-react` version: 0.7.1
- `@inertiajs/inertia-svelte` version: #.#.#

### Describe the problem:
The conversion of the library to TypeScript has made it more opinionated in what type of payload you are allowed to use when using Inertia.patch, Inertia.post etc... The type RequestPayload does not allow the payload to be an array. 

We have endpoints that allow patching and creating a bulk of items, and in these cases we allow payload to be an array.

I do not know if this restriction was by intent to make it more opinionated or simply a mistake when converting to TypeScript.

### Steps to reproduce:

// Allowed
Inertia.patch(`/items`, {});

// These are not allowed
Inertia.patch(`/items`, []);
Inertia.patch(`/users`, [{id: 1, name: 'Fred'}, {id: 2, name: 'Wilma'}]);

**Comment by claudiodekker** [comment]
Hey @Archheretic,

I know this was already discussed in our Discord, but I figured I'd still react and close this issue with a response so that anyone who stumbles upon this has some context as to why it was closed.

To put it simple, we never considered an 'array' as the payload itself to be valid in the first place, but just didn't have a way to convey this until we started using TypeScript. As such, we don't consider this a bug, but can totally understand why from your perspective it might be.

Of course, one could make the argument that it is valid (as documented by https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data), but it's important to keep in mind that Inertia doesn't _have to_ (and even though that's a whole different discussion, arguably even _cannot_) be 100% compliant with the entire HTTP standard.

Long story short, **we consider Inertia requests to require key-value pairs when submitting data**. If you need to post an array, we recommend doing something like `Inertia.patch('/items', { data: [{ your: 'array' }, { of: 'objects' }] })`.

The problem with an array as the payload by itself, is that it's a bit too flexible in that it just 'floats' around. It doesn't have a 'identifier'. Apart from this, it also opens up the door to questions about supporting binary data blobs and other types. I know this is opinionated, and there might be a very niche use-case somewhere that might be limited because of this decision, but Inertia in itself, like Laravel, is opinionated when it comes to certain aspects.

If you absolutely do need to make requests like this with no way around it, I would recommend using a tool like Axios alongside Inertia, but unless something changes our perspective fundamentally this isn't something we want to change going forward.

Thanks!
